### ISSUE TITLE
Tags not being imported

### ISSUE THREAD

**Issue by richardjddavis** [graphpaperpress/Sell-Media#278]
Tags are no longer being imported into keywords.

**Comment by pmolvaer** [comment]
It fails for me too, I use Lightroom to add keywords.. It seemed to work for the first 40 images I uploaded, but left out the 600 other images..

Is there a plugin for Wordpress to extract the keywords from uploaded images, and put them into the wordpress system? Or do I have to manually punch in keywords for 600 images directly in Wordpress?

...
