### ISSUE TITLE
Process manual payments

### ISSUE THREAD

**Issue by zanematthew** [graphpaperpress/Sell-Media#491]
Either check or cash

**Comment by samedgecombe** [comment]
I have been working on an Invoice extension based on your Stripe extension.

**Comment by MYSTERYouse** [comment]
How could I get in touch with you, as I am starting to focus on this one?

**Comment by thadallender** [comment]
Feel free to [contact us](http://graphpaperpress.com/contact/) or even better, if you're wanting to contribute to core, you could just fork the repo and then submit a pull request:

https://github.com/graphpaperpress/Sell-Media/blob/master/CONTRIBUTING.md

**Comment by samedgecombe** [comment]
I have been working on an Invoice plugin, but if you MYSTERYouse are
working on a solution in the Sell Media core that would also be great.

On 29 April 2015 at 16:28, MYSTERYouse <notifications@github.com> wrote:

> How could I get in touch with you, as I am starting to focus on this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graphpaperpress/Sell-Media/issues/491#issuecomment-97448296>
> .
>



-- 
UK mobile: +447929583069
SWE mobile: +46730922298
skype: samedgecombe

**Comment by MYSTERYouse** [comment]
I went with this request to the Slovak team of people who are the founders of the wp.sk community, here is some feedback from them - main question was an addition of secondary payment gateway/manual payment GW:

- there is no API which would allow you to connect another payment gateway - be it a different vendor or self-fulfillment or manual payment
- I was about to suggest a use of the stripe plugin to achieve this, but it seems it is written as a closed system which is re-writing existing stuff inside of paypal extension
- last option that I suggested was to implement a custom switch of transaction that would hold off the email that has to be sent to the customer after successful purchase, this however requires additional GW to be added into processing of these transactions

I am currently reviewing options of EDD that still has few quirks that I would need to fix, but these features along the other ones are present and would allow me to make the online catalog worth running in my enviroment.

**Comment by zanematthew** [comment]
Considering its a "manual" payment, maybe it should just be a "manual" order as well, i.e., When you get paid, mark it as "paid" in the admin, and manually email the customer the file.

**Comment by thadallender** [comment]
Extension created for this purpose. We'll be releasing this week.

**Comment by samedgecombe** [comment]
Great. Thanks.

söndag 8 maj 2016 skrev Thad Allender <notifications@github.com>:

> Extension created for this purpose. We'll be releasing this week.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/graphpaperpress/Sell-Media/issues/491#issuecomment-217724485>
>


-- 
mobile: +46730922298
skype: samedgecombe
