### ISSUE TITLE
Custom Paypal Checkout page options

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#638]
1) Paypal has a feature that allows its users to create a custom payment page by creating a "page style".  More info here: https://www.paypal.com/customize
This "page style" can be passed as variable in the Paypal options array: https://github.com/graphpaperpress/sell-media/blob/master/js/sell_media_cart.js#L923
as
       
       , page_style : "namedStyle"

As long as the 'namedStyle' is defined on the Paypal account then this will switch the presentation of payment pages.

2) The same would also be true for specifying the notify_url (the IPN listener).. If done as part of the checkout, rather than hard set in the paypal account, it again adds some flexibility as it allows an existing paypal account that may already be used for payments from another website to be used. SM currently requires the IPN url to be hard-set within the receiving paypal account... sending it as the notify_url parameter as part of the checkout process avoids having to hard-wire it into the Paypal account. Yes IPN still needs to be activated, but you are not limited to a single IPN notification url, as long as the plugin supports sending it as part of the checkout process.

**Comment by thadallender** [comment]
If there is critical mass for this, we'll add it. But it just adds more steps to the setup process.

**Comment by thadallender** [comment]
I should add: your second request was added in version 2.0.
