### ISSUE TITLE
Image sizes are hard cropping to defined sizes.

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#639]
I thought this had been fixed as per this ticket: https://github.com/graphpaperpress/sell-media/issues/363  Please double check.  Thanks.

**Comment by thadallender** [comment]
This works as intended, but I can see your point. The size that is downloaded is the longest of the two dimensions. The other side of the image just scales accordingly. Otherwise, we'd be cropping image purchases, and thats not good. :-)
