### ISSUE TITLE
Change sell-media-meta-price to sell-media-meta-free-download on free downloads 

### ISSUE THREAD

**Issue by baddjuju** [graphpaperpress/Sell-Media#647]
Or change the text in that div container to Free Download for items that have been selected as free downloads.

Many customers had mentioned that the "starting at price" is confusing when registering for a download. If the plugin could replace that string with text that states "free download" or a css selector that allows a user to remove the string on free downloads only it would provide a better user experience up downloading free images.

**Comment by thadallender** [comment]
Will add a filter in the next version
