### ISSUE TITLE
Limit quantity of downloadable items (i.e. intangible items) to 1

### ISSUE THREAD

**Issue by DebashisTalukdar** [graphpaperpress/Sell-Media#657]
I use Sell Media to license images. I do not use it to sell prints.
When a customer seeks to purchase a license for an image, I feel that since they are purchasing an intangible item, that the customer should only be allowed to buy a single unit of that item.

I was provided with the following CSS code to hide the quantity field in the checkout page. 

#sell-media-checkout-cart th.item-quantity, #sell-media-checkout-cart
 th.item-increment, #sell-media-checkout-cart th.item-decrement,
 #sell-media-checkout-cart td.item-quantity, #sell-media-checkout-cart td.item-increment,
 #sell-media-checkout-cart td.item-decrement { display: none; }

This creates its own set of problems.

When clicking on the "Buy" button, a customer can click on the "Add to Cart" button multiple times, thereby registering as multiple purchases.

![multiple clicks](https://cloud.githubusercontent.com/assets/8828451/4330736/f9ebeb7c-3fb4-11e4-9d83-5a03ac2b62e0.png)

When the CSS is applied, there is no way for the customer to see the quantity of items being purchased, or adjust the quantity to the correct number.

![shopping cart](https://cloud.githubusercontent.com/assets/8828451/4330740/06bfc404-3fb5-11e4-8273-3df0afed7fa3.png)

It also prevents customers from removing an item from the shopping cart altogether, which will result in a very poor customer experience.

What I feel would be the appropriate implementation is for Sell Media to detect whether the purchase was an "intangible item" (such as a downloadable image), and limit the quantity to just 1 for such intangibles. For tangible items (i.e., prints), you would want to allow customers to order multiples of the same item. There is an implementation of this in WooCommerce.

**Comment by MichaelWeb** [comment]
Hi there,
Thank you for the feedback.
The multiple clicks of "Add to cart" button will be addressed in the next update.
