### ISSUE TITLE
Collections Taxonomy Issue

### ISSUE THREAD

**Issue by xannonmedia** [graphpaperpress/Sell-Media#667]
I have been testing this promising plugin, and run into a few issues (most of which i've worked around).
One such issue that I can't work around is the breadcrumb taxonomy issues.

The main one is when a user clicks on "Collections" in the breadcrumb, or navigates manually to the colletions URL it creates a "Page Not Found" error.  This happens on my website, but also on the official DEMO, eg. http://demo.graphpaperpress.com/sell-media/collections

**Comment by thadallender** [comment]
Version 2.0 fixes this. Please upgrade :-)
