### ISSUE TITLE
Licensing options

### ISSUE THREAD

**Issue by sebunderthe** [graphpaperpress/Sell-Media#675]
Hi There,

I'm trying to give different licensing options when buying media. I have 3 parent categories (royalty free, rights managed and exclusive rights managed). When i add child categories they show up in the same drop down on the site and don't add an extra markup to the parent category selected. I'm wanting to create similar options to Getty, Nimia, Shutterstock, etc. Is this possible with this plugin?

regards,

Seb

**Comment by thadallender** [comment]
Each license has to have it's own markup. Child licenses don't apply markup to the parent. If you're looking for a way to categorize your licenses (which is sounds like you are) just prefix the license names appropriately and add specific markup to each license. Example:
Royalty Free: Websites
Royalty Free: Publications
etc....
