### ISSUE TITLE
Translation not loading properly?

### ISSUE THREAD

**Issue by Janolehuebner** [graphpaperpress/Sell-Media#676]
Hi,
I made a sell_media-de_DE.po translation, but when I activate it it only replaces some strings. (see Image - "Einstellungen" (settings) e.g.)
What can I do?
![ss 2015-01-10 at 02 53 58](https://cloud.githubusercontent.com/assets/2589007/5691631/a967c15a-98d1-11e4-8176-6bea1d9c8dc5.png)

**Comment by rickalday** [comment]
This is related to [this ticket](https://github.com/graphpaperpress/Sell-Media/issues/672).  @thadallender  can you push that to master?

**Comment by thadallender** [comment]
Fixed in version 2.0
