### ISSUE TITLE
Search not returning results for certain keywords.

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#677]
User report: https://secure.helpscout.net/conversation/70800437/4343/

**Comment by maharzan** [comment]
The current search method is as follows:

Use the top search field to search product titles
Use the "Collections" search field to limit your search to specific categories
Use the "Keywords" search field to search specific tags and keywords
Use the "Max Price" search field to find products that fit your budget
And finally, broaden your search if you are unable to find results

So, searching for keywords on that main search box shows 0 results. We probably need to change this.

**Comment by maharzan** [comment]
@thadallender what do you think? 

The main input box should to be able to search everything not just title.

**Comment by rickalday** [comment]
the original support ticket has the explanation from the customer.  He also provided an XML import from his site that I used for testing but basically this is what's happening.  We have several items with the same keywords.  The keyword archive displays all items with that keyword (www.domain.com/keyword/keywordname/) but when you search for that keyword using the keyword field in the search you only get one entry in the results.   It doesn't happen for all the keywords which makes less sense.

**Comment by maharzan** [comment]
@MichaelWeb  is working on this on the new branch "new-search".

**Comment by maharzan** [comment]
The customer is also arguing that the searchbox should search keywords. i agree with him and it should basically search everything, not just keywords or titles.

**Comment by thadallender** [comment]
Now searches keywords, titles and content.
