### ISSUE TITLE
Checkout shows twice without a page associated

### ISSUE THREAD

**Issue by mediafish** [graphpaperpress/Sell-Media#680]
Hi, 

I installed the Sell Media plugin 1.9.12 on WP 4.1.1

When I go to Sell Media/Settings and I click the dropdown to select a page of the Checkout Page I have Checkout listed twice eventhough I only created one Checkout page. 

When I go on your demo site on: http://demo.graphpaperpress.com/sell-media/ I also have the Checkout shown twice - don't know if that is related to my problem but it seems like.

Now I only need one Checkout page of course - why is one autmatically listed - something seems not right...

**Comment by thadallender** [comment]
I can't replicate this at all. Can you send screenshots?

**Comment by MichaelWeb** [comment]
I couldn't replicate this problem either.
