### ISSUE TITLE
Getting message "Please activate Sell Media plugin to use this page."

### ISSUE THREAD

**Issue by klosurdo** [graphpaperpress/Sell-Media#684]
Hi I have activated the sell media plugin and am still getting the "Please activate Sell Media plugin to use this page." at the bottom of the lightbox page as well as other pages. Any idea how to fix?

**Comment by thadallender** [comment]
Upgrade to version 2.0 and also upgrade your theme. That will fix it. https://graphpaperpress.com/plugins/gpp-theme-updates/
