### ISSUE TITLE
Print order

### ISSUE THREAD

**Issue by klosurdo** [graphpaperpress/Sell-Media#685]
Ok,
I enter my prints in "order" starting with 4x6 all the way up to 24x36. When I hit save price group it reorders the whole list and that transfers to the pricing box. So prints are not in order from small to large but arbitrarily? Make no sense to me...

**Comment by thadallender** [comment]
Ah, yep! This is fixed in version 2.0. Thanks for reporting it!

**Comment by klosurdo** [comment]
Thanks,

Is there a estimate on the release of 2.0?

Ken

**Comment by thadallender** [comment]
It's available now :-) just visit your upgrades page in WordPress.
