### ISSUE TITLE
Payments not being recorded after PayPal payment

### ISSUE THREAD

**Issue by OwenBannister** [graphpaperpress/Sell-Media#687]
After a successfull paypal payment I am redirected back to my website to a link similar to 
http://www.blueweka.co.nz/?page_id=21&tx=0C882196KA242223J&st=Completed&amt=0%2e50&cc=NZD&cm=0&item_number=

However the page is empty
![image](https://cloud.githubusercontent.com/assets/2774145/7080345/d9657a4c-df84-11e4-988b-ee9114f79e51.png)

Looking at paypal IPN history and my server logs, the IPN seems to be working correctly 
<b>Server Log<b>
![image](https://cloud.githubusercontent.com/assets/2774145/7080351/f91f8814-df84-11e4-88bf-14a5c39ec927.png)
```173.0.81.1 - - [08/Apr/2015:17:01:41 -0600] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 200 1548 "-" "PayPal IPN ( https://www.paypal.com/ipn )"```

the very first payment I made to test the paypal integration worked and the server logs are the same ```173.0.81.1 - - [10/Mar/2015:23:49:32 -0600] "POST /?sell_media-listener=IPN HTTP/1.0" 200 19291 "-" "PayPal IPN ( https://www.paypal.com/ipn )"```

<b>PayPal<b>
![image](https://cloud.githubusercontent.com/assets/2774145/7080376/1f0f9a3c-df85-11e4-8c4a-bd3808a4f8b9.png)
![image](https://cloud.githubusercontent.com/assets/2774145/7080380/30d31f50-df85-11e4-811e-f5a02b5bcfba.png)

The main issue here is that without the payment being recorded, the download links are not being sent so I have to do this manually. It also means that no users are being created in my system.

**Comment by thadallender** [comment]
Please check all 4 items under the PayPal section in the official docs:

https://graphpaperpress.com/docs/sell-media/#paypal

Can you also paste the contents of Sell Media -> Settings -> System Info below?

**Comment by OwenBannister** [comment]
Yep all of those steps seem fine. 

            ### Begin System Info ###

-- Site Info

Site URL:                 http://www.blueweka.co.nz
Home URL:                 http://www.blueweka.co.nz
Multisite:                No

-- User Browser

Browser Name: Chrome
Browser Version: 41.0.2272.118
Browser User Agent String: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Platform: Linux

-- WordPress Configuration

Version:                  4.1.1
Language:                 en_US
Permalink Structure:      Default
Active Theme:             Sell Photos 1.1.5
Show On Front:            posts
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 8   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit

-- Sell Media Configuration

Version:                  2.0
watermark_attachment_url: 
watermark_all: 
watermark_opacity: 50
watermark_scale: 80
watermark_position: centered
mailchimp_api_key: 
mailchimp_list: 0
test_mode: 0
checkout_page: 19
thanks_page: 21
dashboard_page: 25
login_page: 23
search_page: 0
customer_notification: 1
style: light
layout: sell-media-single-two-col
breadcrumbs: 1
plugin_credit: 0
post_type_slug: 
order_by: date-asc
terms_and_conditions: 
admin_columns: Array
default_price: 5
hide_original_price: no
default_price_group: 0
price_group: 
paypal_email: ob2640@gmail.com
currency: NZD
paypal_additional_test_email: 
tax: 
tax_rate: 
from_name: BlueWeka
from_email: info@blueweka.co.nz
success_email_subject: Your Purchase
success_email_body: Hi {first_name} {last_name},
Thanks for purchasing from my site. Here are your download links:
{download_links}
Thanks!
misc: 
free_downloads_api_key: 2e9cbfcdc3375b3b759acfddae5975fe-us10
free_downloads_list: 0051ee90c8
stripe_test_secret_key: 
stripe_test_publishable_key: 
stripe_live_secret_key: 
stripe_live_publishable_key: 
reprints_hide_download_tabs: 
reprints_shipping: shippingFlatRate
reprints_shipping_flat_rate: 
reprints_shipping_quantity_rate: 
reprints_shipping_total_rate: 
reprints_unit_measurement: cm
reprints_default_price_group: 0
reprints_size_option: 

-- Must-Use Plugins


-- WordPress Active Plugins

Akismet: 3.0.4
Contact Form: 3.89
Exclude Pages from Navigation: 1.92
GPP Plugin Updates: 1.0.3
Hello Dolly: 1.6
Insert Headers and Footers: 1.3.2
Insert HTML Snippet: 1.1.1
MOJO Marketplace: 0.6.1
Sell Media: 2.0
Sell Media Expander: 1.0.2
Sell Media Magnifier: 1.0.2
Sell Media MailChimp: 1.0.5
Sell Media Watermark: 1.1.5
WP-Mail-SMTP: 0.9.5

-- WordPress Inactive Plugins

Jetpack by WordPress.com: 3.3
Sell Media Advanced Search: 1.0.6
Sell Media Commissions: 1.3
Sell Media Discount Codes: 1.0.1
Sell Media Free Downloads: 1.1.6
Sell Media Reprints Self Fulfillment: 1.3.5
Sell Media Stripe: 1.0.9

-- Webserver Configuration

PHP Version:              5.4.39
MySQL Version:            5.5.42
Webserver Info:           Apache

-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          50M
Post Max Size:            50M
Upload Max Filesize:      50M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           N/A

-- PHP Extensions

GD:                       Supported
cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

### End System Info ###

**Comment by OwenBannister** [comment]
Happy to email through account details so you can log in

**Comment by thadallender** [comment]
Sure. I'd love to take a look. Please email us at support@graphpaperpress.com

**Comment by OwenBannister** [comment]
Emailed

**Comment by thadallender** [comment]
I replied via our support ticket, but just wanted to follow up here also:

It looks like the payment did in fact show up in the WordPress/Sell Media Payments page, but likely did so after you arrived at the Thanks page. So, this is why the Thanks page was blank.

PayPal IPN notifications occasionally happen AFTER PayPal has redirected buyers to your website. There doesn't appear to be a consistent time in which this happens. It just varies. So, in version 2.0.1 (released yesterday) we added a message that lets customers know their purchase is pending and provides them with a refresh button to check the payment status. When they click refresh, PayPal will likely have delivered the IPN if for some reason it was originally delayed.

1.

**Comment by OwenBannister** [comment]
Cheers for that. I think there might still be an issue as only that single payment (the first one I made) has ever shown up and there have been 20+ purchases. It seems like its responding to paypal with a 200 but not actually recording that it was a successful payment.

Also looking at the thanks url, is it supposed to be populated with an item number?
`http://www.blueweka.co.nz/?page_id=21&tx=36G43897M49595520&st=Completed&amt=0%2e50&cc=NZD&cm=0&item_number=`

**Comment by OwenBannister** [comment]
Also got this sent through so im guessing that this is triggered when the thanks page is empty 

We have some good news and bad news. First the good news: Somebody just purchased from your store! The bad news: Your website was unable to retrieve transaction ID from PayPal. This is typically easy to fix. Please see these tips for resolving this issue: https://github.com/graphpaperpress/Sell-Media/issues/670#issuecomment-89428248

**Comment by MarcoTribuz** [comment]
excuse me, i have the same issue :/

**Comment by thadallender** [comment]
Please try upgrading to version 2.0.2, which was just released today. If that doesn't work, please double check that your server doesn't have a firewall preventing PayPal IPNs.

**Comment by OwenBannister** [comment]
IT WORKS :) Thanks so much for the support guys, you've been awesome. Out of curiosity what was the cause of the issue? I've spent so much time trying to work it out :)

**Comment by thadallender** [comment]
Some servers didn't like the SSL cert file, which is used to communicate with PayPal securely. It was difficult to pinpoint, because it worked for about 3/4 of users. Glad it's working for you now!

**Comment by MarcoTribuz** [comment]
it Works! :D

Il giorno mer 22 apr 2015 alle ore 23:30 Thad Allender <
notifications@github.com> ha scritto:
