### ISSUE TITLE
Change of "Post Type Slug" leads to item pages not retrievable (404)

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#688]
I had no "Post Type Slug" set in the settings so the items used "items" as permalink.
I added two items and could access them from all pages (search, collections etc.).
Later I changed "Post Type Slug" to "stock-artikel" and I could no longer open the previously opened items. I received a 404 error instead.
Also new items added after the cahnge can not be accessed. I also used other slugs like "test" but no item could be opened any more.
I then removed the slug again (empty) and I was able to open the item pages again after this change.

**Comment by thadallender** [comment]
Just visit the Settings -> Permalinks and it will flush your Permalinks and things will be accessible.

**Comment by TheShihan** [comment]
Thanks, this did work. Just visiting the WP permalinks page made the item pages working again (even with post type slug). Maybe this flush can be triggered when the user changes that setting of "sell media"?

**Comment by thadallender** [comment]
We'll add that to a future release. Thanks @TheShihan!
