### ISSUE TITLE
Make all texts translatable

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#694]
Not all texts are currently translatable. For example some texts like "continue shopping" or "By clicking "Checkout Now", you are agreeing to our terms of service." on the "checkout" page, "Size", "License" on the "buy" page.
Also the "more" link seems not to be translatable and the exif information headers on the item detail page.
On the wordpress page it was told, that changes were made and now more texts can be translated but I don't see that change in the new version (2.0.3) and also the file here on github is 6 months old.

**Comment by rickalday** [comment]
This string too: https://github.com/graphpaperpress/Sell-Media/blob/3af2dee906a58661c04f4d1bf47a3459817585ee/inc/class-search.php#L285

**Comment by thadallender** [comment]
Version 2.0.4 makes the strings above translatable. If a string is missed, please send a link to the file and I'll add it. Fixed by 079385e52989a0ad28b4b975dffc80857f8707f5
