### ISSUE TITLE
Client proofing

### ISSUE THREAD

**Issue by MYSTERYouse** [graphpaperpress/Sell-Media#695]
Guys, I can remember there has been a feature that allowed users to download proof images saved to lightbox to view them on their computers. However I cannot find any refference to it in the source files.

This is a note next to checkbox when creating new collection:
"Check this to allow clients with password access to download items in this collecton as proofs. Clients must add an item to their Lightbox in order to download proofs. A record of which images were downloaded will be sent to both the site admin and the client via email."

**Comment by thadallender** [comment]
The proofs download feature for collection was never fully implemented. We found flaws in the reasoning for it. It makes more sense to be saved as post meta, not taxonomy meta (which is what a collection is).

I'm starting to scope out how client proofing should work. We honestly have so many different opinions for how this should work, that it's going to be difficult to please everyone. I'm aiming for a solution that solves 80% of user needs. Edge cases will have to be custom projects.

Here are my thoughts:

ASSUMPTIONS
1. In the admin, an item must be password protected to enable client proofing
2. In the admin, a new checkbox will appear in the Options meta box below Pricing fields when adding/editing a single item.
3. In the front-end, if a user has supplied a correct password to access the post, and client proofing is enabled for this item, the Buy button changes to a Download button allowing users to download the high-resolution image.

Thoughts @MYSTERYouse ?

**Comment by thadallender** [comment]
You can do client proofing with the Access Control extension that we just released: http://graphpaperpress.local/plugins/sell-media-access-control/
