### ISSUE TITLE
Unlimited Discount code cannot be used

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#698]
When I create a new discount code that has no start and end date and no usage count set (empty value) the discount code cannot be used. Message returned is that the code is no longer valid. When I enter a start and end date the code can be used.

Shouldn't the code also be usable without a date range? A code that can be used multiple times without date restrictions.

**Comment by thadallender** [comment]
The next release of Sell Media Commissions will have this feature.
