### ISSUE TITLE
Download Link Not Working

### ISSUE THREAD

**Issue by ElsieRymer** [graphpaperpress/Sell-Media#700]
I have the most recent updates made to Sell media, and there is still no link in client's inbox to the actual image AFTER they've paid. Please advise
![snip20150507_35](https://cloud.githubusercontent.com/assets/12315318/7529327/10a2007a-f4fc-11e4-8445-fabc71c2f4e0.png)

**Comment by ElsieRymer** [comment]
@thadallender, any update on this? I'm going to have to go a different route with no response, though I don't want to.

**Comment by thadallender** [comment]
@ElsieRymer Looks like you're missing the required `{download_links}` tag in your email. Paste what you have here on your Sell Media -> Settings -> Email -> Email Body setting.

**Comment by ElsieRymer** [comment]
I'm afraid that's not it, @thadallender 
This has been there the entire time. Could it be something else?

![snip20150513_53](https://cloud.githubusercontent.com/assets/12315318/7622980/0e608d1a-f99b-11e4-8c23-a7f023c038f7.png)

**Comment by thadallender** [comment]
Two things:

1. Are these purchases really coming from Sell Media? Or are they purchases using the same PayPal receiver account accidentally triggering Sell Media emails?
2. Who is purchasing these? If you are doing test purchases, you cannot use the same PayPal account for buyer and seller.
3. Have you checked all 4 of the possible problems here? https://graphpaperpress.com/docs/sell-media/#paypal

**Comment by drodmun** [comment]
Hi, in my case that part works, even the link works, but the image downloaded it says is corrupted...
I add the info to the same thread since the error is related to "Download Link Not Working".

I attached screenshots of the email sent, the failure trying to open it with Paint and windows default image viewer...

![screenshots](https://cloud.githubusercontent.com/assets/9948927/7744802/880bfa1c-ffa6-11e4-86a9-10f3e9c63ee6.png)

Also, the link of download: 
http://goo.gl/duWr1b

**Comment by thadallender** [comment]
@drodmun What kind of image file is this? JPG? What mode? Images should be in sRGB mode. It won't work in print mode (Adobe RGB).

**Comment by drodmun** [comment]
sRGB

**Comment by thadallender** [comment]
Can you attach the full-size image here? I want to see if I can replicate it.

**Comment by drodmun** [comment]
There!
![3](https://cloud.githubusercontent.com/assets/9948927/7765576/817133fc-005f-11e5-8b5d-8cbcffaf569f.jpg)

**Comment by thadallender** [comment]
@drodmun I cannot replicate this issue. My guess is that your missing a dependency on your server. Please do this to help me pinpoint the issue:

1. Check if WordPress itself is able to resize images. Sell Media relies on functions in WordPress for image resizing. If Sell Media cannot resize the images, that likely means that none of your images in WordPress are being resized either. Then, we know that your server is missing a required library such as PHP Image Magic (does all the image resizing).
2. Do a new test purchase and try to download the purchased file.
3. Immediately check your server error.log file. Contact your web host if you don't know where this error log is saved.
4. Copy the System Info page (Sell Media -> Settings -> System Info) and email the info to support@graphpaperpress.com.
