### ISSUE TITLE
SVGs get width and height of 1px

### ISSUE THREAD

**Issue by mintcanary** [graphpaperpress/Sell-Media#702]
Trying out SVGs, via https://wordpress.org/support/plugin/add-full-svg-support It pretty much works, but in some places (main image on front-end, Sell Media sections in admin) img has `width="1" height="1"`, which is obviously not ideal.

**Comment by thadallender** [comment]
It's likely a limitation of the plugin you referenced above. The plugin above says it requires shortcodes to use, and has fallback support for PNG, but you must use Shortcode to specify the PNG file. I'm not seeing how this pertains to Sell Media.
