### ISSUE TITLE
IPTC title and description not being read

### ISSUE THREAD

**Issue by icenando** [graphpaperpress/Sell-Media#705]
Only keywords are being read from IPTC data. Title and description fields are being ignored.

**Comment by thadallender** [comment]
Pertaining to galleries? Or singles? If your merely wanting titles and descriptions to show on galleries, the next version will have this.

**Comment by icenando** [comment]
It's pertaining to the sell media plugin: when you 'add new' and upload an image, the Title and Caption fields are there (see attached screenshot). When you click 'Sell All Selected Images' and either 'Save Draft' or 'Publish' it, only the keywords are automatically read from the IPTC data. The Title and Caption fields for that image are blank in the 'edit product' page.
![screen shot 2015-05-21 at 19 34 28](https://cloud.githubusercontent.com/assets/12436042/7756125/fa636920-fff0-11e4-871f-7289412bece2.png)

**Comment by thadallender** [comment]
Thanks for explaining. The next version will display the image title and caption below the image on single and gallery pages. See the attached.
![Uploading Screenshot 2015-05-21 15.22.35.png…]()

**Comment by icenando** [comment]
Cool! Thank you. Looking forward to seeing the updates.
