### ISSUE TITLE
Clients can't logout

### ISSUE THREAD

**Issue by icenando** [graphpaperpress/Sell-Media#706]
Clients can log in, but not logout. If the "remember me" box is checked, that's a perpetual login right there (apart from deleting cookies).

**Comment by thadallender** [comment]
Fixed by 66c7c7219b0647b3a9fb4ce95b1de902b99d61a2

**Comment by icenando** [comment]
Thanks. Will there be a sell-media plugin update coming out for this, or should I change it myself. If the latter, please advise on how to do it.

Kind regards,
Nando.

**Comment by thadallender** [comment]
A new version will be out soon

**Comment by icenando** [comment]
Excellent - thank you!
Nando.
