### ISSUE TITLE
i want old upload system in sell media

### ISSUE THREAD

**Issue by tusharbd** [graphpaperpress/Sell-Media#708]
Before I uploaded images sell media and they shown as single images but now I can not. If I upload images they are showing at first in a Folder. But I don't want it. I want to upload as like before, all single images not in a folder.

**Comment by thadallender** [comment]
You can download the old version here: https://github.com/graphpaperpress/Sell-Media/releases/tag/1.9.8

**Comment by tusharbd** [comment]
but new version is updated with other features. I want to upload as like before, all single images not in a folder.

**Comment by thadallender** [comment]
Then just upload 1 image.

**Comment by tusharbd** [comment]
i see, but i want upload bulk images, is it possible?

**Comment by tusharbd** [comment]
please send me the sell media 2.0 version
