### ISSUE TITLE
Adhering to Wordpress Standards

### ISSUE THREAD

**Issue by d-g-h** [graphpaperpress/Sell-Media#709]
> Adhere to WordPress Coding Standards

We can do this via the commandline or via the commandline with a build tool (Gulp, Grunt, etc).

I hope this creates and helps maintain a cleaner code base. I hope this will not introduce bugs. phpcbf can help with spacing issues, and the syntax of control structures. More serious concerns will need to identified, and handled though.

Using phpcs coupled with the installed coding standards outlined below
```
phpcs -i
```
*The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Extra and WordPress-VIP*

...I was able to identify these errors and warning with `phpcs --extensions=php . > phpcs-log.txt`

https://gist.github.com/d-g-h/f589f1f56e52530ec9fe#file-phpcs-log-txt

phpcs can be installed using a variety of methods outlined here https://rtcamp.com/tutorials/standards/php/code-sniffer/, I went with brew

**Comment by thadallender** [comment]
Thanks for this dude! The dev branch actually already has all necessary Grunt/phpcs/wpcs/i18n tasks integrated. We should be all set.

**Comment by d-g-h** [comment]
@thadallender No problem. I updated phpcs the other day so this task got a little easier. Thanks to the phpcs people, and wp standards people. 

I didn't include task runner code as I wasn't sure whether it was Grunt or Gulp, but I did commit fixes from `phpcbf -vvvv --extensions=php . #Changes files in place, careful please` here.

Just testing the :ocean: for ya. Careful out there.

https://github.com/d-g-h/Sell-Media/commit/2141f54577c9242e1c35371f4774e6415b924e6e

**Comment by thadallender** [comment]
I'm gonna push out an update tomorrow. If you want to pull the dev branch and submit a pull request with these changes I'll add you as a contributor :+1:

**Comment by d-g-h** [comment]
Sorry for the delay. I missed this. Will do though. I think I can squash most of the warning/notices/suggestions automatically. Either way, I will report back with some stats here and in the PR before testing.
