### ISSUE TITLE
Theme tailored for video clip sales

### ISSUE THREAD

**Issue by cineflite** [graphpaperpress/Sell-Media#710]
All WP themes cater for photography stills however there does not exist a theme designed specially for video clips. This seems odd considering the huge explosion in video media online. 

I offer my own situation as a user case. I have a growing archive of several hundred high-value clips from 10-40 seconds long but no easy way to market them online. Key features of such a theme would include:

- Easy bulk upload of watermarked low res versions and full res clips with metadata including airframe, camera, lens, resolution, codec, duration, record date, location coordinates, frame rate, bitrate and a list of tags.
- Searchable by keyword, category, location (interactive map), or other metadata.
Search results should maximise viewable clips in a grid (ideally you could run your mouse over the clip to see a quick succession of keyframes like an animated gif).
- clicking a clip will open the video in either a lightbox, play in situ, or open in a workspace area on the screen. 
- the visitor should be able to mark certain clips as a favourite that can later be checked together for final sorting.
- watched clips could be marked as already watched to save multiple view by accident by the visitor.
- The detail page of a clip includes all the metadata plus an map of where it was taken. 

The only other nice feature to include would be the option to allow multiple media providers to submit their footage for sale on the same site.

The closest site I've found that does some of this is airstoc.com but even their is room for much improvement.

If you implement something like this please let me know!

Thanks guys

**Comment by thadallender** [comment]
Version 2.2, which is due out early this week, adds improvements for video handling. Watermarking and file compression need to be handled before upload. It's simply not in the scope of what this plugin can do. Desktop software exists for that purpose. Here are the main additions/changes for video:

1. Adds a video preview URL field if the uploaded file is a video.
2. Videos searchable by Keyword
3. Videos play in a popup and on single page
4. Videos can be saved to Lightbox
5. File Metadata is shown for videos on single page. Note: Location data isn't shown for privacy issues.
