### ISSUE TITLE
Missing translatable strings

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#711]
The new update fixed a lot of the missing translatable strings issues but there are still some more.

Please include those strings in the next POT file release:

Collections page: text when hovering a collection image is not translatable (description/amount and starting price)... also: it's a bit inconvenient that you must hover collection thumbs to see their name and the description seems to be covered by a layer which makes in partly unreadable. Would be best if on this page the name of the collection would be displayed by default:
![sell_media_collections](https://cloud.githubusercontent.com/assets/511436/8043704/16d057ea-0e28-11e5-918c-446351aa10e1.png)

On checkout page, "continue shopping" and "terms" part is not translatable:
![sell_media_checkout](https://cloud.githubusercontent.com/assets/511436/8043706/16f491b4-0e28-11e5-8ae8-9d9e17829334.png)

The search results text, title and button is not translatable:
![sell_media_search_results](https://cloud.githubusercontent.com/assets/511436/8043705/16f460e0-0e28-11e5-95db-847890e78984.png)

On the item details page on the right side the "Category" and "Date" is not translatable:
![sell_media_item_details](https://cloud.githubusercontent.com/assets/511436/8043708/16f5db1e-0e28-11e5-9eb3-3401f5f33ae1.png)

On the buy dialog the text "License" and "Size" is not translatable, also there is no space between the currency and the amount value:
![sell_media_buy_dialog](https://cloud.githubusercontent.com/assets/511436/8043707/16f517f6-0e28-11e5-96d7-96408928461b.png)

On the blog page the buttons for going back and to the archive are not translatable (tooltip text which appaers when hovering buttons):
![sell_media_back_archive](https://cloud.githubusercontent.com/assets/511436/8043709/16f7418e-0e28-11e5-84b1-c08d5211470e.png)

**Comment by thadallender** [comment]
Thanks for reporting this. These have been added:

1. Continue shopping
2. Terms
3. License
4. Size

All other strings aren't coming from Sell Media, but rather, your theme. What theme are you using?

The new translatable strings in Sell Media will be available in the next release.

**Comment by TheShihan** [comment]
OK, thanks. I'm using the GPP Intra theme. Maybe I missed something there but I thought I translated everything in there as well.

**Comment by TheShihan** [comment]
Indeed I there was also an issue with my GPP Intra translation file. I switched my locale to de-CH but I forgot to change the file names for the Intra translations.
