### ISSUE TITLE
Stock photography theme: wrong lowest price in collection

### ISSUE THREAD

**Issue by icenando** [graphpaperpress/Sell-Media#712]
When I hover over the collection, I see the message that there is '1 image in <Collection Name> collection starting at $20'. It's actually starting at $3: $20 is the original size. Smaller sizes are cheaper. By choosing to hide the original price I can go around this issue, but by doing so the buyer doesn't get the option of buying the image in its original size in the drop down list (when clicking 'Buy'). The message has to show the lowest image price, or no price at all.

**Comment by thadallender** [comment]
Make sure that you're using the most recent version of this theme. Version 1.2.8 includes a fix for the collection page template lowest price display.
