### ISSUE TITLE
Aliases for keywords and translatable keywords

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#713]
Not an issue but a feature request. Would be great to give more power to the keywords.

I'm thinking of things like:
- Keyword hierarchy
- Keyword aliases
- Keyword translations
- Improved search by keyword (for exmaple: similar keywords etc.)

**Comment by thadallender** [comment]
Keywords, by nature, are hierarchical. Collections are hierarchical. Keywords are like tags. Can you provide a use case for hierarchical keywords? I'm not clear on how this would ever be used.

Version 2.0.5 dramatically improves keyword searching (especially for galleries).

**Comment by TheShihan** [comment]
I was having in mind a system for keywords like the one istock uses. For
example when you enter sky you have to select between the weather phenomen
or the TV channel called sky. Also a user could also search in german for
"Himmel" and would find images tagged with "sky".
Am 12.08.2015 03:26 schrieb "Thad Allender" <notifications@github.com>:
