### ISSUE TITLE
Can no longer bulk upload multiple photos to a collection

### ISSUE THREAD

**Issue by OwenBannister** [graphpaperpress/Sell-Media#714]
Might be missing something that changed recently, but when I upload a folder of images it creates them as a single item in a collection. I was expecting that it would create seperate items in the collection.

Also I cannot navigate though to the items, as the link doesn't appear to be clickable. This is after updating the theme.
http://www.blueweka.co.nz/collection/it-heavy-hitters/

Cheers

**Comment by thadallender** [comment]
We added Gallery support to Sell Media in version 2.0. Having two similar features (Galleries and Add Bulk) confused some people, so we removed Add Bulk from core Sell Media and made it into an extension.

**Comment by OwenBannister** [comment]
Cheers
