### ISSUE TITLE
No watermark on images

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#717]
I have activated the GPP watermark plugin and specified the path to the watermark image (PNG with a width of 191px), rest of the settings are default.

Unfortunately no watermarks apear on my images, e.g.:
http://www.schielke.ch/stock-artikel/schiefer-turm-von-pisa-1/ (JPG image)

I reactivated the plugin but no change. Don't know what I am doing wrong. Don't using a CDN and even deactivated the magnifier plugin.

I use sell media 2.0.4 and latest version of Watermark plugin.

There is no .htaccess file directly inside my /wp-content/uploads folder - should there be one or has this been changed?

**Comment by thadallender** [comment]
I'm seeing a JS error for a "cross-site scripting" issue. Is the watermark image located on the same website? Both the watermark image and the image that are being watermarked need to live on http://www.schielke.ch

**Comment by rickalday** [comment]
@TheShihan in the Watermark settings check that the option to watermark all images is NOT selected.  Let us know if that makes a difference.

**Comment by TheShihan** [comment]
Checkbox was already deactivated but Thad pointed me in the right direction. I forced the image/article page to https and now the watermark is there. Seems the http version of the page could not load an image which was served propably by https. Have you guys any suggestions regarding using https - do you recommend a plugin to force the sites/images to https?

**Comment by thadallender** [comment]
Cool. Yes, I've used this in the past when there are https/http issues: https://wordpress.org/plugins/wordpress-https/

**Comment by TheShihan** [comment]
Ah, I already use this plugin :-) but I didn't add my article slug to the box which forces those links under that url to https... now this is done and it works, so I don't have to force every article manually to https :+1:
