### ISSUE TITLE
Improved Watermarking

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#719]
A feature request for improved watermarking, actually multiple features for it:
* Watermarking not by JavaScript but forced by serving the sell media article images processed on the server. Currently a user can simply disable JavaScript to get the image without a Watermark - not the best protection but at least a small obstacle.
* Watermarking not compatible with expander plugin: when I hover images and the biger version shows up (during the expander plugin) the expanded image does not contain the watermark.
* More options for the watermark: e.g. like other stock agencies are displaying the images, possibility to add the watermark multiple times layered over the images (tiles) or diagonally.

My suggestionw would be to apply the watermark already to the lower resolution images as soon as the main original image is moved to the (protected) /uploads/sell_media folder. Maybe on an admin page there should be options to regenerate all the lower resolution images when desired, in case there is a new watermark that should be applied to already uploaded images or if the watermark should be removed.

**Comment by thadallender** [comment]
Thanks for the feedback! There is already a plugin that watermarks the actual file which should probably work out nicely work you:

https://wordpress.org/plugins/image-watermark/

I'm gonna close this issue, but feel free to open it up again if the plugin above doesn't work out for you.

**Comment by HaraldWalker** [comment]
The old version of sell-media-watermark did that, then that version stopped working (and I didn't notice!) and now the new version uses javascript and leaves the photos unprotected. Am very disappointed.

**Comment by julianmatz** [comment]
@HaraldWalker Same here. The watermark plugin was working fine until it somehow got upgraded. It's unusable now - (a) because it has slowed things down a lot and causes the browser to freeze; and (b) because I can simply right-click the image and open the original image in a new tab.

**Comment by julianmatz** [comment]
Also, the https://wordpress.org/plugins/image-watermark/ plugin doesn't work for me. I'm guessing that images would have to be re-uploaded. That's not really an option...

**Comment by thadallender** [comment]
Our Watermark extension now includes the ability to protect files either using Javascript (client side, dynamic, non-destructive to images, but slightly less secure) or using PHP (server-side, watermarking only happens during file upload, very secure). You can control this setting on your Sell Media -> Settings -> Misc tab.
