### ISSUE TITLE
Redirected to sell media documentation when trying to change price or price group of product

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#721]
When I add an article/product and click inside the price input field or the price group selection I will get redirected to the following documentation page of sell media:
https://graphpaperpress.com/docs/sell-media/#add-bulk

This shouldn't happen.

**Comment by thadallender** [comment]
Weird. This definitely shouldn't be happening. I can't replicate it at all. Can you attach annotated screenshots?

**Comment by TheShihan** [comment]
It happens when I click inside the field for the price (directly or on one of the arrows) or the filed for the price group assignment:
![redirecttodocs](https://cloud.githubusercontent.com/assets/511436/9437205/2c2ee3cc-4a55-11e5-850d-47ba8da56fe8.gif)

The fields are highlighted here:
![redirect](https://cloud.githubusercontent.com/assets/511436/9437233/6527a024-4a55-11e5-9446-6b79965eaf0e.png)

**Comment by thadallender** [comment]
Ok, I think I know what's going on. I think you have an invalid string translation. Please check that you've properly translated this string:

https://github.com/graphpaperpress/Sell-Media/blob/master/inc/admin-items.php#L64

There is a link in the sentence. Make sure that you've closed the link properly with an </a>.
