### ISSUE TITLE
Message "Important updates are available for ... sell media ..." doesn't vanish

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#722]
Inside wp-admin on the top of the settings page of sell media (2.0.4) is always a message like "Important updates are available for ... sell media ...." and it can be clicked away by clicking on the "x" on the right side of the message.
But when I return later to the page again it is there again. Have clicked it away multiple times but it always reappears which is annoying.

Message should only appear once and never again if clicked away... until there are really new updates available - which is not the case currently.

**Comment by thadallender** [comment]
Which extension is this happening with?

**Comment by TheShihan** [comment]
Sell media free downloads and stripe.
Am 12.08.2015 00:55 schrieb "Thad Allender" <notifications@github.com>:

**Comment by thadallender** [comment]
Disable the GPP Plugin Updates plugin if it's active. We added auto-updates in core Sell Media a few versions back. Also, make sure that the names of each plugin are exactly like they are named in our product downloads (via our Dashboard.)
