### ISSUE TITLE
Sell Limited Edition Images

### ISSUE THREAD

**Issue by deryckvs** [graphpaperpress/Sell-Media#724]
Please develop a 'stock control' plugin for the 'Sell Media' plugin.

In order to sell limited edition images (very important element of fine art photography) we need to be able to control the number of images purchased.

The number of images in an edition will differ from photographer to photographer from one offs (1/1) through to editions of 5/10/20/100/100 or any other quantity at the discretion of the photographer.

Using the example of an edition of 5 the clients/customers will buy 1/5, 2/5, 3/5, 4/5 and 5/5. Once 5/5 is sold then the edition is complete and no further will be sold increasing the value of the artwork in the edition.

I think that using/developing a 'stock control' plugin that works with 'Sell Media' plugin in which the quantity is inputed by the artist and when the final artwork is sold the artwork is 'sold out/out of stock' would work.

**Comment by thadallender** [comment]
Added!

https://graphpaperpress.com/blog/limited-edition-prints/
