### ISSUE TITLE
Sell Media returns results for images that aren't products

### ISSUE THREAD

**Issue by ericbrissette** [graphpaperpress/Sell-Media#726]
The search is returning results for products, but also for attachment pages for tons of images on the site, which of course leads to results for images that can't be purchased.  It looks to an end user like the search returns lots of duplicate results with the products and attachment pages for the same image side-by-side.

**Comment by TheShihan** [comment]
Have the same issues, a lot of duplicates in the search results because of this.

**Comment by TheShihan** [comment]
This is what a search looks like (with duplicates):
![screen shot 2015-09-23 at 23 23 05](https://cloud.githubusercontent.com/assets/511436/10059233/22e11724-624a-11e5-9924-da85f4d04185.png)

For example one link points to this (attachment):
https://www.schielke.ch/?attachment_id=2582

And the other (the one we want to keep) looks like this:
https://www.schielke.ch/stock-artikel/black-angus-342/

**Comment by Scheefe** [comment]
Hi,

I have the same issue here and the demo of the plugin shows that behaviour as well: https://graphpaperpress.com/demo/?project=Stock%20Photography

I tried to track it down and it seems, that it has something to do with the sell_media_content_loop(), which gets called with too much IDs.
I just couldn't find out, where that call is located.

Are there any news on this issue yet?

**Comment by samedgecombe** [comment]
I have a solution for this and will post this as a pull request. The logic is that we need to append to searches that we are looking for sell_media_items, or attachments to sell_media_items, but not any other type of attachments e.g. unattached images or model release images.

**Comment by thadallender** [comment]
We've fixed this on the dev branch and will be merging with the master branch and releasing to WordPress.org this week.
