### ISSUE TITLE
Paypal IPN receives 403

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#728]
I guess this is probably an issue on my side. Paypal worked fine in test-mode but in live mode the user can pay for an item but when he returns to the site he receives a message that order was successful but without the download details.
Also no email from mysite to the customer is being sent (but paypal email is sent). Also the transaction is not showing up under the purchases inside sell media.

Btw, I tried it with a normal paypal account and also a Business Account (not pro).

I see in the log that the IPN from paypal gets a 403 response:
> 173.0.81.1 - - [31/Aug/2015:09:20:00 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )" 

CURL is available/supported, stripe is working like a charm. Also I'm in live mode and using a live email address. I tried to make sure everything is setup according to the documentation (https://graphpaperpress.com/docs/sell-media/ "Pay Pal" section) and I guess it might be that my hoster blocks IPNs but I'm not sure about how to bypass this. What must be added to .htaccess and to which .htaccess file, the one in the root directory of the wordpress installation? Should it work with the line "Allow from .paypal.com" or is it another setting?

**Comment by thadallender** [comment]
@TheShihan My guess would be that your web host is rejecting PayPal IPN because it doesn't have a user-agent (a common technique some bots use). Just add this to the .htaccess in your WordPress directory:

Allow from .paypal.com

Add that inside your server block somewhere and let me know if that resolves the 403.

**Comment by TheShihan** [comment]
Unfortunately I don't see any change, tested it again just some minutes ago, message in log looks the same (403 error):
> 173.0.81.1 - - [01/Sep/2015:08:50:17 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
> 192.0.84.33 - - [01/Sep/2015:08:50:50 +0200] "HEAD / HTTP/1.1" 200 5023 "-" "jetmon/1.0 (Jetpack Site Uptime Monitor by WordPress.com)"
> 173.0.81.1 - - [01/Sep/2015:08:51:38 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )" 

And also in IPN history inside paypal:
![paypal_403](https://cloud.githubusercontent.com/assets/511436/9597977/45e965d4-5087-11e5-9cd5-06f33a4431a5.png)

Maybe I understood how to configure .htaccess wrong. I edited this file inside the root of the wordpress directory:
![htaccess](https://cloud.githubusercontent.com/assets/511436/9598008/9837905e-5087-11e5-849d-ce957ebf6153.png)

And this is the file's content:

    Allow from .paypal.com
    
    # BEGIN WordPress
    
    # BEGIN Math Captcha
    <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} POST
    RewriteCond %{REQUEST_URI} .wp-comments-post.php*
    RewriteCond %{HTTP_REFERER} !.*www.schielke.ch.* [OR]
    RewriteCond %{HTTP_USER_AGENT} ^$
    RewriteRule (.*) ^http://%{REMOTE_ADDR}/$ [R=301,L]
    </IfModule>
    # END Math Captcha
    
    <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
    </IfModule>
    
    # END WordPress

I don't know what you  mean by "server block", so maybe this is the issue :-)

**Comment by thadallender** [comment]
Ok, let's test something here. Open up this file:

https://github.com/graphpaperpress/Sell-Media/blob/master/inc/gateways/php-paypal-ipn/IPNListener.php

Right below line 109, which says curl_setopt($ch, CURLOPT_HEADER, true); add this:

```
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');
````

Try another real transaction and let me know if it works.

**Comment by TheShihan** [comment]
I changed the file `/wp-content/plugins/sell-media/inc/gateways/php-paypal-ipn/IPNListener.php`

and added:
> curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');

below the line you mentioned, then I performed another live transaction but still a 403 seems to occur:
> 173.0.81.1 - - [01/Sep/2015:20:58:50 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
> 173.0.81.1 - - [01/Sep/2015:20:59:02 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
> 173.0.81.1 - - [01/Sep/2015:20:59:24 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )"
> 173.0.81.1 - - [01/Sep/2015:21:00:06 +0200] "POST /index.php?sell_media-listener=IPN HTTP/1.0" 403 9304 "-" "PayPal IPN ( https://www.paypal.com/ipn )"

Is there another way to get more error details? Some kinde of debugging? Shall I give you logon credentials for the admin section?

**Comment by thadallender** [comment]
I wish there was more that I could do to help you, but the issue is pretty clear to me:

Your server is rejecting the IPN. Unless that gets resolved PayPal is not going to be able to deliver the IPN. I'd recommend contacting your web host and ask why they are preventing PayPal from delivering IPN payloads to your website. It could be that they have a Firewall or something that is preventing PayPal from reaching your server.

**Comment by TheShihan** [comment]
I spoke with the support from the web hosting provider but I don't think he can help me. He now asks me to add a user agent to the paypal request, which I already did. Maybe tomorrow I can speak with another supporter from them :-)

Btw, I also receive a lot of the following emails:
> Subject: Invalid IPN
> --------------------------------------------------------------------------------
> [09/01/2015 9:00 PM] -  (curl)
> --------------------------------------------------------------------------------
> 
> --------------------------------------------------------------------------------

They are sent from my wordpress site but I don't know what they want to tell me and why does it say "Invalid IPN"?

**Comment by thadallender** [comment]
If you'd like us to log into your site and test, feel free to send WP admin and FTP/SFTP/SSH credentials to support@graphpaperpress.com. This really does seem to be server/firewall related.

**Comment by TheShihan** [comment]
Sent you the login credentials *FingersCrossed*

**Comment by TheShihan** [comment]
Issue occured because of wordpress plugin "WP-Spamshield". Option "Disable for misc. forms" in WP-Spamshield had to be activated and issue is now gone. PayPal can now reach the listener.
