### ISSUE TITLE
Please make text "continue shopping" and "By clicking..." translatable

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#729]
On the cart page ("Warenkorb/Kasse" on screenshot below) where you can checkout the articles the text in the lower right corner is not inside the translation file (POT) of Sell Media 2.0.6. Also the text below that "Clicking 'Checkout Now'..." is not translatable. Please make this strings translatable. 

![screen shot 2015-09-09 at 22 18 49 copy](https://cloud.githubusercontent.com/assets/511436/9773467/b4d5e5a0-5742-11e5-9b96-b8d4a9ef5e8f.png)

Also, when on that same page and cart is empty there is also the text "... Continue shopping" (maybe same text), but this one is also not translatable.

**Comment by rickalday** [comment]
Hey @TheShihan I have an updated version of the POT file on this [branch](https://github.com/rickalday/Sell-Media) that includes those strings.

**Comment by TheShihan** [comment]
Thanks, those strings can now be translated, but I noticed that now "Credit Card" doesn't use the translation anymore ("Kreditkarte" above is now "Credit card"). Also "Discount Code" seems now to be missing and maybe others I didn't check.

**Comment by thadallender** [comment]
The Sell Media Stripe plugin has this translation string:

"Credit Card"

```php
<?php _e( 'Credit Card', 'sell_media' ); ?>
```

Perhaps you need to update your Stripe extension? Let me know if that works for you. Closing this for now since it's working for us.
