### ISSUE TITLE
Sell Media Exif: Wrong Camera Information

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#730]
I use the Stock Photography with Sell Media 2.0.6 and display the Exif information with the Sell Media Exif widget next to the image.

All data inside the widget looks fine except the first entry "camera information". Instead of the camera used it seems to display a part of the image's caption (in the example below it was "...flying in th*e air*". This is the case for all images:

![screen shot 2015-09-23 at 22 51 37](https://cloud.githubusercontent.com/assets/511436/10058525/2d79516e-6246-11e5-87f4-b2c0cbe4bab6.png)

**Comment by thadallender** [comment]
Sell Media 2.1 should fix this. Please reopen and attach an example image if the problem persists after that. Thanks!
