### ISSUE TITLE
Bulk Edit Commissions on Admin Page

### ISSUE THREAD

**Issue by samedgecombe** [graphpaperpress/Sell-Media#733]
I have contributors who upload their own images using a certain WP post type, but they cannot change their commission level (and should not), but I have to go and do this individually for each item which is time consuming. Is they a workaround?

**Comment by thadallender** [comment]
I propose we rework this extension a little to rely on core WordPress roles and capabilities. Then, we would add this:

1. If user is a "contributor" - show new "commission rate" field on each user profile page that only a site ADMIN can modify.
2. Contributors cannot see or change their assigned commission rate on either their profile page or when adding new Sell Media entries.
3. When they publish new Sell Media entries, we first check if the item itself has a custom commission rate, if so we use it. If it doesn't, then we check their default user commission rate and use it. If no commission rate exists, no commission is given.

Would this work for you @samedgecombe ?

Also, we've been working hard on version 2.1. Feel free to test the DEV branch of Sell Media.

All extensions are hosted at BitBucket. Each extension has it's own Issue Tracker. Here is the issue tracker for Sell Media Commissions:

https://bitbucket.org/graphpaperpress/sell-media-commissions/issues?status=new&status=open

**Comment by thadallender** [comment]
Closing this ticket here since we'll be adding this to Sell Media Commissions. The repo/issue tracker for Sell Media Commissions is located here:

https://bitbucket.org/graphpaperpress/sell-media-commissions/issues?status=new&status=open
