### ISSUE TITLE
Collection and search result as thumbnails

### ISSUE THREAD

**Issue by lanselotbg** [graphpaperpress/Sell-Media#737]
When I use [sell_media_list_all_collections details="true" thumbs="true"] on a page to show thumbnails of all collections and click on any of the collections thumbnail I want to see all images in this collection as a thumbnails again, instead this I see large images. Same when I use search. I want thumbnail as result of a search and I have large images on a result page? Is there any way to change this?

**Comment by thadallender** [comment]
The way Search results and Archive pages are displayed is dependent on how your theme styles that page. That said, this commit e22657cb65b45e77fe90d8ba8ed5842e018f4f09 will now force all WP installs with Sell Media activated to use the archive.php template in Sell Media. It might, however, require some additional CSS styling to fit your theme.
