### ISSUE TITLE
tags with special characters are not included in search

### ISSUE THREAD

**Issue by peckinpah** [graphpaperpress/Sell-Media#738]
Any keyword with a special character (like for example the "ø" in the Danish word "rød") attached to a product is *not included* when doing a standard search. This is a huge issue for us because it effectively renders the search function unusable for a lot of our content which is tagged with special characters :-/  

Does anyone know of a workaround for this issue?

![screen shot 2016-01-04 at 14 38 22](https://cloud.githubusercontent.com/assets/16540485/12090630/0933ada8-b2f1-11e5-9e8f-f44630f0d7c9.png)
![screen shot 2016-01-04 at 14 39 00](https://cloud.githubusercontent.com/assets/16540485/12090631/0933e516-b2f1-11e5-932e-f39ed38ecff7.png)

**Comment by thadallender** [comment]
1241498c6abc7396e3f4eda6aec3f4364e4bac14 fixes this. We're releasing this update this week.
