### ISSUE TITLE
got this error on activation (dev branch)

### ISSUE THREAD

**Issue by cmans** [graphpaperpress/Sell-Media#744]
The plugin generated 1008 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

with Twenty Fifteen theme.

Deactivating and reactivating didn't show that error.

**Comment by thadallender** [comment]
We cannot replicate this. If you can provide exact steps to reproduce, feel free to reopen.

I DID...
I SAW...
I EXPECTED...

**Comment by cmans** [comment]
I redid this today on a clean wordpress install. Got similar error:

The plugin generated 1014 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Created New DB and assigned the db to wp-config.php. Cloned and Activated Sell Media dev branch and got the error. So, I think this error is every much a bug coming from somewhere.

**Comment by codearryaas** [comment]
Please pull dev branch. Issue has been fixed.
