### ISSUE TITLE
Size list empty after update to 2.1

### ISSUE THREAD

**Issue by Janolehuebner** [graphpaperpress/Sell-Media#750]
After I updated there where no sizes in the list anymore and because of that i can not add anything to the cart. also tried a fresh reinstall of sell media and theme - same thing
![ss 2016-02-14 at 10 45 29](https://cloud.githubusercontent.com/assets/2589007/13036658/2328c076-d36d-11e5-8517-ef81dbeae0ae.png)

**Comment by thadallender** [comment]
How can I replicate this issue? What price settings? Please send screenshots of your price settings and individual item page settings.

**Comment by Janolehuebner** [comment]
I will test a complete wordpress reinstall later today. attached a few screenshots. Let me know if you need anything else

![ss 2016-02-15 at 12 55 22](https://cloud.githubusercontent.com/assets/2589007/13048185/7840b146-d3e4-11e5-8933-f3a8ef0333a6.png)
![ss 2016-02-15 at 12 56 10](https://cloud.githubusercontent.com/assets/2589007/13048186/7843921c-d3e4-11e5-8f2d-988d1c5bd4d7.png)
![ss 2016-02-15 at 12 57 12](https://cloud.githubusercontent.com/assets/2589007/13048184/7840398c-d3e4-11e5-86ec-8d6204e2fe8a.jpg)

**Comment by MYSTERYouse** [comment]
I used to keep only one dimension set in the settings (for example max width).

While ago there was a similar issue that was not showing it due to similar setting.

Try to keep only the max width set and make sure your item has this dimension?

**Comment by thadallender** [comment]
We will be pushing out 2.0.1 this morning. It should fix your issue.

**Comment by thadallender** [comment]
All set @Janolehuebner?

**Comment by Janolehuebner** [comment]
just updated - fixed, thanks
