### ISSUE TITLE
Styling issues with "Sell Media Recent Items" entries with 2.1

### ISSUE THREAD

**Issue by TheShihan** [graphpaperpress/Sell-Media#752]
I have the stock photography theme and placed the "Sell Media Recent Items" in the footer widget 2 zone (in the screenshot below called "Neue Stock Fotos"). Before 2.1 the items displayed nicely (like thumbnails). Now the images are quite big and no longer just thumbnails. This ruins the apperance of the site.

Maybe this has also something todo with the new Quickview?

Have a look at how it looks now:

![screen shot 2016-02-28 at 21 57 26](https://cloud.githubusercontent.com/assets/511436/13381866/d42afb4c-de66-11e5-9e54-ac853175c644.png)

**Comment by MYSTERYouse** [comment]
I believe, this has been already fixed in the recent update - try updating to the latest release, on my web it is fixed.

**Comment by thadallender** [comment]
Yes, this has been fixed. #resolve
