### ISSUE TITLE
Changes of "0" item pricing

### ISSUE THREAD

**Issue by MYSTERYouse** [graphpaperpress/Sell-Media#754]
I am trying to find the logic behind updating the prices and use of price groups, but somehow it does not allow me to change items on a per-item basis.

Settings in SM backend: 
Original price: 1
Hide Original price: No
Default Image Price Group: None

SM individual item uploaded earlier
Price: 1
Price group: none

No matter what I do, the system does not allow me to change the price of an already existing item. This only works when you upload the item and state the price 0. On the individual item, it always reverts back to "1". Basically the system does not allow you to go down to 0 from any other price. 

It does not relate to the "Original price" set in the back-end.

**Comment by thadallender** [comment]
Looking into this now.

**Comment by thadallender** [comment]
We tested using your exact same settings. It's working fine for me and another developer. What version are you using?

**Comment by thadallender** [comment]
Ok, we see it now. If you change a number like 5.00 to 0, it reverts to 5.00. If you change 5.00 to 0.00, it works. We'll get it fixed.

**Comment by MYSTERYouse** [comment]
Ahh, ok. So it needed to be with two digits. Did not come to my mind to test it this way.

**Comment by thadallender** [comment]
We fixed this around version 2.1.6, so I'm closing this.
