### ISSUE TITLE
My images mixed in Collections!

### ISSUE THREAD

**Issue by louipstockhoto** [graphpaperpress/Sell-Media#756]
Hello guys,

I have stock photography theme and i updated sell media 2.1.5.
My images mixed in collections and the search box not working!
My in "Budapest" collection is London images! :D 

Questions

What do i do? :) 

Thanks!
Loui

**Comment by thadallender** [comment]
You likely just need to update your extensions and your theme. If that doesn't work, feel free to email our support team support@graphpaperpress.com

**Comment by louipstockhoto** [comment]
Yes. I updated extensions... I wrote! Rick checked my website but no decipherment! :( 
My theme 1.2.9.

louistockphoto.com

**Comment by thadallender** [comment]
Please [download the dev branch of Sell Media](https://github.com/graphpaperpress/Sell-Media/archive/dev.zip) and replace the old version with this one. Please confirm it fixes your issue.

**Comment by louipstockhoto** [comment]
Ok, I try today! Thanks!

**Comment by louipstockhoto** [comment]
Ok! This working! Thanks guys! :) 
But the search not working! ;)

**Comment by thadallender** [comment]
Search works for Keywords by default. An option exists for searching other fields, but using Keywords is highly recommended, since it's accurate 100% of the time.

If search still isn't working, please post a new issue so we can keep issues focused around a specific issue, rather than multiple issues added after the fact.

Thanks!

**Comment by louipstockhoto** [comment]
Hi,

Thanks guys! The search works!

Thanks! 😊
Loui

2016. máj. 8. dátummal, 16:40 időpontban Thad Allender <notifications@github.com> írta:
