### ISSUE TITLE
Permanently delete in wordpress don't delete the file in /sell_media

### ISSUE THREAD

**Issue by Miranio** [graphpaperpress/Sell-Media#757]
It's an issue I came across while trying to setup sell media.

Steps to reproduce

1) upload a picture
2) set the picture as a product ( sell media then copy it in the hidden directory )
3) publish the product
4) delete the product
5) empty trash ( **notice that the original picture don't get put back in the /upload/2016/ directory** )
6) delete permanently the picture in the wordpress media section

After deleting permanently the picture, it do delete all the sizes in /uploads/2016/ but it keep the original file ( that can be quite big ) in /uploads/sell_media/

More on this, if I try to upload again the file ( that was modified but kept the same name ) SellMedia will serve the old version of the file as it detect the file name is already in /sell_media/

Workaround : manually delete the file in /uploads/sell_media/ after deleting it in wordpress. Very time consuming and prone to error.

**Comment by Miranio** [comment]
Further exploration of this issue

line 509 of admin_items.php is
    $attached_file = get_post_meta( $postid, '_sell_media_attached_file', true );

There is no such post meta of "_sell_media_attached_file". The only meta available is "_sell_media_attachment_id"

Probably the main source of the issue here.

**Comment by Miranio** [comment]
https://github.com/Miranio/Sell-Media/tree/patch-1

That would be my proposed solution

**Comment by thadallender** [comment]
Thanks for this! It looks good. Mind testing this again against our DEV branch and then submit a PULL REQUEST? I'll merge into DEV and then into MASTER and deploy the update.

**Comment by thadallender** [comment]
No need to send a pull request @Miranio . The commit above fixes it.
