### ISSUE TITLE
Caught in Update Plugin Loop - Sell Media Reprints

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#758]
Sell Media Reprints Plugin Version 2.1.1
WordPress 4.4.2 running Albedo version 1.3.3.

Tells me there is a new version 2.1.1 available (even though I have 2.1.1 installed).
1) I click update now
2) It says updated
3) Log out / log in
4) The plugin is highlighted orange but it is not asking to update
5) Refresh the page
6) Now it is asking to be updated again.

This loop continues if I click update now.  

![screen shot 2016-04-03 at 8 13 03 pm](https://cloud.githubusercontent.com/assets/18253020/14236440/77e65210-f9db-11e5-8a7f-e1574c923912.png)

![screen shot 2016-04-03 at 8 19 07 pm](https://cloud.githubusercontent.com/assets/18253020/14236447/8edfd6c6-f9db-11e5-9e3a-99ea8aa04679.png)

![screen shot 2016-04-03 at 8 21 40 pm](https://cloud.githubusercontent.com/assets/18253020/14236449/98761998-f9db-11e5-8122-0f6ef4e48bd2.png)

![screen shot 2016-04-03 at 8 22 18 pm](https://cloud.githubusercontent.com/assets/18253020/14236451/a25ca21a-f9db-11e5-9809-841cd36f6fc5.png)

**Comment by AoxoA-Create** [comment]
It also happened with Sell Media Discount Codes plugin.  When I had both of them activated, the first one I tried to "update" would move to step 2 above.  The second one I would try to update would fail.   It did not matter which one I tried first.  The second one always failed.  And back to the loop, etc...

The other GPP plugins are running without "update" loop issues:.  

![screen shot 2016-04-03 at 8 41 58 pm](https://cloud.githubusercontent.com/assets/18253020/14236516/e88e2d3e-f9dc-11e5-8f16-2ece8f2c6837.png)

**Comment by AoxoA-Create** [comment]
1. More testing:  
2. deleted Sell Media and the extensions. 
3. updated to the current version of GPP Theme Albedo (version 1.3.4)
4. Reinstalled Sell Media
5. Logged out/ logged in, refreshed, etc... (everything seemed stable)
6. Reinstalled Sell Media Reprints
7. Logged out/ logged in, refreshed, etc... (everything seemed stable)
8. Entered my license keys to enable automatic updates
9. (can't remember if i tested anything) shut down computer for the night.
10. Start up computer, etc...
11. Update Loop Problem back
12. Took out my license key information (disabled GPP's automatic updates)
13. "Updated" plugin
14. Logged out/ logged in, refreshed, etc... (everything seemed stable)

**Comment by AoxoA-Create** [comment]
Back to testing.  In the 24 days since I last posted I have not had any issues with the "update plugin loop" issue because I disabled GPP's automatic updates.  During this time I deactivated, deleted and manually scrubbed everything to do with W3 Total Cache plugin.

1. Today I enabled GPP automatic updates by entering my license key information
2. I am now caught back in the  "update plugin loop"

![screen shot 2016-04-28 at 12 55 30 pm](https://cloud.githubusercontent.com/assets/18253020/14906649/61030a00-0d83-11e6-9d85-52fca370f01a.png)
![screen shot 2016-04-28 at 12 58 08 pm](https://cloud.githubusercontent.com/assets/18253020/14906650/6104aeb4-0d83-11e6-8256-6e9f1f5de36f.png)
![screen shot 2016-04-28 at 12 58 27 pm](https://cloud.githubusercontent.com/assets/18253020/14906647/61015e80-0d83-11e6-835f-578b84a86eb0.png)
![screen shot 2016-04-28 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/18253020/14906646/60ff6c42-0d83-11e6-808f-ac8013468f66.png)
![screen shot 2016-04-28 at 12 59 07 pm](https://cloud.githubusercontent.com/assets/18253020/14906648/61023224-0d83-11e6-86ea-8bf7b5f209c7.png)

I I can just deactivate the GPP auto updates after a round of updates.  Then enable the feature when I want to check for updates.  But there must be a solution somewhere.....

**Comment by thadallender** [comment]
This happens when the folder name is different from the plugin folder that is downloaded via auto-updates. Please change the name of the folder in plugins for sell-media-reprints and then visit the Plugin page again make sure that Sell Media Reprints plugin is active. Then visit Updates and auto-update.

**Comment by AoxoA-Create** [comment]
Change the name of the folder in plugins to what?  Change from "sell-media-reprints" to ???

Here are screen shots of the folders

![screen shot 2016-05-08 at 9 41 19 am](https://cloud.githubusercontent.com/assets/18253020/15098372/7ed99ee2-1501-11e6-8add-45dd47d4b9bb.png)

![screen shot 2016-05-08 at 9 41 57 am](https://cloud.githubusercontent.com/assets/18253020/15098373/85117e2e-1501-11e6-8236-e5c1b4054fa0.png)

**Comment by thadallender** [comment]
It should be named sell-media-reprints. Also, delete the gpp-plugin-updates plugin. It's no longer necessary since core Sell Media adds auto-updates. That might the cause of the issue.

**Comment by AoxoA-Create** [comment]
So, the folder "sell-media-reprints" should be named "sell-media-reprints"?  If that is the case, I don't have to rename it ;-)

My gpp-plugin-updates was deactivated. I went ahead and deleted it.

Still have the update loop.  Notice the Sell Media Water Mark failure as well:

![screen shot 2016-05-08 at 10 01 01 am](https://cloud.githubusercontent.com/assets/18253020/15098489/c017de16-1504-11e6-9863-637f5c2cd466.png)

![screen shot 2016-05-08 at 10 01 27 am](https://cloud.githubusercontent.com/assets/18253020/15098492/c87dbc4c-1504-11e6-88fc-2ce893a41cdf.png)

![screen shot 2016-05-08 at 10 01 35 am](https://cloud.githubusercontent.com/assets/18253020/15098498/dddfddcc-1504-11e6-8753-3d727a2a27a3.png)


![screen shot 2016-05-08 at 10 01 56 am](https://cloud.githubusercontent.com/assets/18253020/15098504/e7c1650e-1504-11e6-886b-42f83b9696b7.png)

![screen shot 2016-05-08 at 10 01 56 am](https://cloud.githubusercontent.com/assets/18253020/15098507/ed9b57aa-1504-11e6-848d-bf210ae09a97.png)

![screen shot 2016-05-08 at 10 02 25 am](https://cloud.githubusercontent.com/assets/18253020/15098508/f2dad34e-1504-11e6-9992-70a400e5575d.png)

Here is a screen shot of my GPP folders in plugins:

![screen shot 2016-05-08 at 10 06 24 am](https://cloud.githubusercontent.com/assets/18253020/15098513/058062de-1505-11e6-986a-7568ea853428.png)

**Comment by AoxoA-Create** [comment]
I was able to get the update to stick on Sell Media Watermark. The failure happened if I tried to update Sell Media Watermark second (after trying to update Sell Media Reprints).  

The update worked when I left Sell Media Reprints alone and just updated Sell Media Watermark.  In other words, I updated Sell Media Watermark first instead of attempting the update after updating Sell media Reprints.

**Comment by thadallender** [comment]
Ah, so it's only updating Sell Media extension one at a time for you? Are all extensions now updated?

**Comment by AoxoA-Create** [comment]
No.  Sell Media Watermark would fail to update if I tried to update directly after attempting the Reprints update.  Once the loop started again I did not attempt a Reprints update---instead I updated Watermark,  then refreshed the browser, etc...  So, it seems, the update failure on Watermarks was somehow happening because of trying to update Sell Media Reprints first.  Confusing.  

said another way:
1) notices to update Reprints and Watermark
2) First update Reprints, then update Watermark.  Reprints indicates a successful update.  Watermark indicated a failed update.
3) refresh browser, etc...
4) loops back with notices to updates Reprints and Watermark
5) update Watermark (without updating Reprints).  Update of watermark successful.
6) Reprints still caught in loop

**Comment by AoxoA-Create** [comment]
![screen shot 2016-05-08 at 12 22 35 pm](https://cloud.githubusercontent.com/assets/18253020/15099383/b390cd1e-1519-11e6-81c6-98a173871da2.png)

After clicking update

![screen shot 2016-05-08 at 12 22 52 pm](https://cloud.githubusercontent.com/assets/18253020/15099389/c1c818f6-1519-11e6-8334-cc22e0d30df5.png)

After refresh browser

![screen shot 2016-05-08 at 12 23 05 pm](https://cloud.githubusercontent.com/assets/18253020/15099390/ca49bf3e-1519-11e6-9b90-4e881cf8e4e2.png)

Refresh browser again, back to square one:

![screen shot 2016-05-08 at 12 23 16 pm](https://cloud.githubusercontent.com/assets/18253020/15099392/d4c3dc56-1519-11e6-90d7-299625b974c7.png)

Caught in loop.  Here are my plugin folder names:

![screen shot 2016-05-08 at 10 06 24 am](https://cloud.githubusercontent.com/assets/18253020/15099400/f97fe1ac-1519-11e6-9d02-6b988dbcfebd.png)

**Comment by AoxoA-Create** [comment]
Appears to be fixed with update to Sell Media Version 2.2.1

**Comment by AoxoA-Create** [comment]
It appears that the issue is solved with the update to Sell Media Version 2.2.1.

**Comment by AoxoA-Create** [comment]
Went 5 days without a problem.  Now the loop is back.  Notice how it is wanting to update to the same version that is installed.

![screen shot 2016-05-16 at 10 26 33 am](https://cloud.githubusercontent.com/assets/18253020/15302900/f6cdeab4-1b7a-11e6-8d30-1c755eeeb08f.png)

After clicking update

![screen shot 2016-05-16 at 10 26 48 am](https://cloud.githubusercontent.com/assets/18253020/15302913/0198f4fc-1b7b-11e6-850b-dda6820a673e.png)

After refresh browser

![screen shot 2016-05-16 at 10 27 05 am](https://cloud.githubusercontent.com/assets/18253020/15302925/091fef28-1b7b-11e6-9f8e-18f5e9fae1f7.png)

Refresh browser again, back to square one:

![screen shot 2016-05-16 at 10 27 16 am](https://cloud.githubusercontent.com/assets/18253020/15302944/17e971a0-1b7b-11e6-85a0-773fd9d729c6.png)

Caught in loop.

**Comment by thadallender** [comment]
We fixed this in the most recent version of Reprints.
