### ISSUE TITLE
Items have a cost of 0 until the item is updated manually 

### ISSUE THREAD

**Issue by OwenBannister** [graphpaperpress/Sell-Media#759]
Price is set to $5
![image](https://cloud.githubusercontent.com/assets/2774145/14370346/80915348-fd81-11e5-9fea-b23e03d947ed.png)

but on the show page it is $0
![image](https://cloud.githubusercontent.com/assets/2774145/14370366/9ea98e7c-fd81-11e5-9070-13d2166fa549.png)

This causes it to be able to be freely downloaded

It can be fixed when manually updating an item but not by bulk updating

Running on Version 2.1.6

**Comment by OwenBannister** [comment]
Hey guys, has anyone been able to look into this?

**Comment by codearryaas** [comment]
Please check if you have used "Sell media Free download" addon. If you check free download option then it will be replace the price.

**Comment by thadallender** [comment]
This only happens is you're using the Free Download extension. Make sure you're using the most recent version of that extension and that the item isn't set as a free download.
