### ISSUE TITLE
Invalid IPN email (Test Mode) - Empty Thanks Page, Cart Still Full after PayPal Redirect (Live Mode)

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#760]
This might be a bug (i am not sure).  I sent a message to GPP support but have not heard back in over 84hours.  So, I thought I might try here to see if anyone could help.

I am using Sell Media Version 2.1.8 on WordPress 4.4.2

I am in Sell Media Test Mode.  I am able to add to cart, checkout and pay via PayPal sandbox account, etc...  When I go back to the website from PayPal:
1.     My website “Thanks” page is empty
2.     The cart still has the items in it.
3.     Received an email from WordPress with “Invalid IPN” in the subject line.
 
I checked for these possible problems:
1.     I use a valid PayPal Sandbox Test account and valid sandbox email in Sell Media Settings..
2.     My Apache server is CULR and GD enabled (I have PHP 5.4).
3.     I added “Allow from .paypal.com” to my .htaccess file as the first line.
 
I contacted my hosting company and asked these questions:
1.     Does my web host have a firewall that is blocking incoming pings from PayPal? 
2.     Does my server block all incoming pings (IPN notifications) that dodn’t have a User-Agent defined?  
3.     Is my server set up to block incoming pings when the User-Agent is not explicitly set?  

The answers were, 1) no 2) There are no blanket blocks. 3) There are no blanket blocks.

The PayPal sandbox IPN Simulator indicates the IPN was sent and the handshake was verified. The IPN history in PayPal indicates it was sent. Transaction history in the buyer and seller accounts is correct and successful.

So, is this normal?  If not how can I fix the issue.  Any ideas are welcome.  Please advise.

**Comment by thadallender** [comment]
Thanks for the detailed report. This is definitely not normal. PayPal's Sandbox itself has lots of issues. Testing in Live Mode might be helpful here. Please do the following:

1. Add your real PayPal email to Sell Media -> Settings.
2. Turn Sell Media into Live Mode, not Testing Mode.
3. Set the price of a product to $1.
4. Send me link to a product that I can buy and I'll make a purchase.

**Comment by AoxoA-Create** [comment]
Thanks for the quick reply.  Here is a test product:  http://aoxoa.co/items/test-live/

If you would like admin access, I am open to that.

**Comment by thadallender** [comment]
Just made a purchase. Based on what I'm seeing, your problem is likely one of the following:

1. You have PayPal's Auto-Return feature turned on. Turn it off. If you have a URL set, remove it.
2. You have PayPal Payment Data Transfer set. Turn it off also. If you have a URL set, remove it.

Also, please confirm that you have the [sell_media_thanks] shortcode on the Thanks page. I believe you do, but just confirm.

I'm 99% sure that that problem is because of a custom setting you have at PayPal. Please check 1 & 2 above.

**Comment by AoxoA-Create** [comment]
I never thought i would say this, I am in the 1%.

1. Auto Return was off, and no URL established
2. Data Transfer was off, no option to set URL 
3. Confirmed [sell_media_thanks] shortcode was on the Thanks page

I tested the process as well.  PayPal did not direct me back to the website. I received transaction emails, etc... Earnings Report and Payment in Sell Media show the transactions.  PayPal did not direct me back to the website.

I was using my PayPal secondary email in Sell Media Settings.  I updated it to use my primary PayPal email (just in case).  Ready to test again.

![screen shot 2016-05-04 at 12 02 28 pm](https://cloud.githubusercontent.com/assets/18253020/15022712/89e3556a-11f2-11e6-8b06-4114381417c8.png)

![screen shot 2016-05-04 at 12 01 00 pm](https://cloud.githubusercontent.com/assets/18253020/15022717/9101ca3e-11f2-11e6-901b-fbe87f5bcbf6.png)

![screen shot 2016-05-04 at 11 38 04 am](https://cloud.githubusercontent.com/assets/18253020/15022725/9a1e51c8-11f2-11e6-8a81-9156c3dde1c5.png)

**Comment by AoxoA-Create** [comment]
On my second test, I was redirected but the Thanks page is empty and the cart still has an item in it.

![screen shot 2016-05-04 at 12 25 35 pm](https://cloud.githubusercontent.com/assets/18253020/15022898/753c3220-11f3-11e6-8f2a-55f4ae8585a2.png)

**Comment by thadallender** [comment]
Interesting. Good to know.

Here is the error log:

http://aoxoa.co/ipn_errors.log

It appears that there's a problem with cURL. Let's make sure it actually exists on your server. Create a file called "info.php" and add this to it:

```<?php phpinfo(); ?>```

Put it in the web root of your website, next to wp-config.php and link me to it here.

**Comment by AoxoA-Create** [comment]
http://aoxoa.co/info.php

**Comment by thadallender** [comment]
Thanks. So we've isolated the issue to CURL, which is used to communicate between your server and PayPal. That "handshake" isn't working for some reason.

Based on my research, it could be related to PayPal's plans described here:

https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1914&viewlocale=en_US

That page says for you to **"Contact your provider (your web hosting provider) to ensure they support TSL 1.2 and HTTP/1.1"**

Who is your web host anyway?

You might also ask your host to do the things described in the section titled "Verify your systems at https://tlstest.paypal.com!"

Let me know what they say.

**Comment by AoxoA-Create** [comment]
Hosting is at https://domainnameroundup.com.  I think they are basically GoDaddy.com by another name.

I don't think I have an SSL Certificate. Do I need one?  Anyway, I'll contact the hosting people and report back.

**Comment by thadallender** [comment]
Unless PayPal changed recently, you should be able to use without a SSL. That said, if you're selling anything on your site, you should def. use SSL for customer piece of mind and trust.

You can get a free SSL certificate with free account at CloudFlare.com

**Comment by AoxoA-Create** [comment]
Well, I encountered a Mr. Smarty pants on the phone support of my Hosting service.  When asked about TSL 1.2 and HTTP/1.1 he said they are always up to date with PayPal requirements.  Basically, he would not actually check.  No matter what I said he would not check.  He just repeated that there couldn't be a problem because they would be flooded with calls, etc, etc, etc...

So, asking him to "Verify your systems at https://tlstest.paypal.com!" was a no go--i didn't even try.

I gave him the link---http://aoxoa.co/ipn_errors.log---to see the logs.  He said it must be an issue with the plugin.  He does not see any errors with the server cURL.

**Comment by AoxoA-Create** [comment]
I spoke with another support tech at my hosting company.  Yes, they do support TSL 1.2 and HTTP/1.1.  Although, none of those are relevant to our issue because TSL 1.2 is used with SSL (which I don’t have) and HTTP/1.1 is for a windows server (I use Linux).

Isn’t the “handshake” working if we are routed back to my site with proper updates to Sell Media’s Earnings Report and Payment sections?  Plus, PayPal's sandbox IPN Simulator indicated the IPN was sent and the handshake was verified.

The issue of items being left in the cart......

Here is the summary:

Sell Media Version 2.1.8
WordPress 4.4.2

Test Mode Properly set up:  
1.	using proper PayPal sandbox emails, etc. 
2.	My Apache server is cULR and GD enabled (I have PHP 5.4)
3.	I added “Allow from .paypal.com” to my .htaccess file as the first line.
4.	Web host does not block incoming pings from PayPal.
5.	Web Host does not use blanket blocks.

Test Mode Results (with issue):
1.	Able to checkout and pay via PayPal (sandbox account)
2.	Upon redirect back to my site, 
    a.	“Thanks” Page displays “Thank You”
    b.  **Cart still has items in it**
    c.	 No indicators in Sell Media (Earnings Report and Payment) that a test transaction occurred.
3.	WordPress sends email with Subject “invalid IPN” in subject line
4.	The PayPal sandbox IPN Simulator indicates the IPN was sent and the handshake was verified. 
5.	The IPN history in PayPal indicates it was sent. 
6.	Transaction history in the buyer and seller accounts is correct and successful.

Live Mode Properly set up
1.	Using real PayPal email in Sell Media -> Settings. 
2.	Sell Media is in Live Mode, not Testing Mode
3.	In PayPal:
    a.	Auto Return was off, and no URL established
    b.	Data Transfer was off, no option to set URL 
4.	Confirmed [sell_media_thanks] shortcode was on the Thanks page

Live Mode Results
1.	Able to checkout and pay via PayPal 
2.	Upon redirect back to my site, 
    a.	“Thanks” Page displays “Thank You”
    b.	**Cart still has items in it**
    c.	Sell Media (Earnings Report and Payment) indicates a transaction occurred.
3.	Successful transactions via PayPal and all email notifications sent

**Comment by thadallender** [comment]
Thanks for the detailed report. Let's focus on Live Mode since PayPal's Test Mode is buggy and provides inconsistent results.

The Thank You page, Cart, and Earnings Reports admin page all rely on the same IPN notification from PayPal. When fix the issue, it will solve all three problems at once.

Three things to check:

1. Do you have a caching plugin installed? All pages that collect "dynamic data" like the Checkout, Lightbox and Thank You should NOT be cached. Disable caching  and do another test.

2. When you are redirected from PayPal to the Thank You page, are their query variables set in the url? For example, you should be redirected from PayPal with things like this in the url:

 http://aoxoa.co/thank-you/?pid=1234&pgroup=75&type=download.....

3. Did you add SSL to your site?

Let me know. Very eager to get this solved for you.

**Comment by AoxoA-Create** [comment]
Ok.  Focusing on Live Mode.

1. Sell Media Reports (Earnings Report) and Payments admin pages work fine.
2. Thank You Page might be working (?). What should be there?
3. Cart does not empty

Checked three things:

1. Do I have a caching plugin installed?  No.  I use to have W3 Total Cache but I deactivated, uninstalled and scrubbed all traces of it I could find. 

2. When I am redirected from PayPal to the Thank You page, are their query variables set in the url?  No.  It looks like this:  http://aoxoa.co/thank-you/

After I click the button to redirect, PayPal displays a page thanking the customer for the order.  A security popup shows up.  After I click continue I get redirected back to my site.

![screen shot 2016-05-06 at 4 48 27 pm](https://cloud.githubusercontent.com/assets/18253020/15087093/6815e820-13ab-11e6-9459-337fb30f4857.png)

3. Did I add SSL to my site? Not yet. Doing it correctly will be a process and I am still closing the learning curve.  Also, I can’t have interruptions to the site for at least another month.

**Comment by thadallender** [comment]
OK thanks. PayPal is not sending any transaction data in the URL. That is the problem. I just tested on our dev site and this is the URL PayPal redirects me to:

http://testing.graphpaperpress.com/sell-media-thanks/?tx=81H25990DB020822Y&st=Completed&amt=16%2e50&cc=USD&cm=0&item_number=

Without a tx parameter, no transactions are recorded in Sell Media and the cart will remain populated.

Enable your Payment Data Transfer setting in PayPal and turn on Auto Return. PayPal should be doing this automatically. Explicitly setting those options forces PayPal to use these options. I'm at a loss for why your account isn't doing this automatically.

**Comment by AoxoA-Create** [comment]
To enable Auto Return and Payment Data Transfer PayPal says:

"You must enter a properly formatted Return URL. If you do not enter a properly formatted Return URL, which includes the Return URL requirements, Auto Return will not be turned on and applied to your Website Payment pages."

What URL should I use?  The Thank you page URL?

**Comment by thadallender** [comment]
Yes, your thank you page.

**Comment by AoxoA-Create** [comment]
Ok, we are getting somewhere.

The thank you page display the following BUT the cart shows 1 item in the menu (i did not check at this point to see if something was actually in the cart

![screen shot 2016-05-06 at 5 51 03 pm](https://cloud.githubusercontent.com/assets/18253020/15087973/a026a18e-13b3-11e6-9a77-bd4f887e0172.png)

I clicked the refresh link.  It displayed the item, etc and the cart still indicates 1 item in the menu.

![screen shot 2016-05-06 at 5 51 41 pm](https://cloud.githubusercontent.com/assets/18253020/15087981/c2b945c6-13b3-11e6-8238-406df200e1f1.png)

I checked the cart.  Nothing is in there, but it indicates 1 item on the menu.

![screen shot 2016-05-06 at 5 52 06 pm](https://cloud.githubusercontent.com/assets/18253020/15087994/eec60410-13b3-11e6-9eec-27694499d4db.png)

**Comment by AoxoA-Create** [comment]
Adding to the message above.  I closed the browser (which deletes cookies) and reopened.  The cart showed 0 item in the menu.  Bought an item.  After redirect cat on menu indicated 1 item.

I added an item.  Cart still showed 1 item in menu.  I increase the qty and cart showed 2 items in menu.  Was able to reduce items to zero.

**Comment by thadallender** [comment]
Great. So it sounds like updating your settings at PayPal fixed it?

The cart total in the cart remaining looks be a bug with caching. We'll fix this in the next release.

**Comment by AoxoA-Create** [comment]
Updating the PayPal settings fixed the main issues.  Thanks ;-)

**Comment by thadallender** [comment]
Feel free to post feature requests here as a new issue. Our official roadmap is here:

https://trello.com/b/3p0uPSnB/sell-media-roadmap
