### ISSUE TITLE
Feature Request - Clear Cart Button

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#761]
It would be useful for users to be able to clear the entire cart quickly by pressing a button.
Maybe even deleting line items without having to reduce the qty to zero, etc...

**Comment by thadallender** [comment]
We've talked about this before. Since there's already a way to delete items from their cart, we don't think that adding yet another way to delete items enhances the checkout experience. Reducing the number of buttons, options and text, specially on the checkout page, is a high priority for us in optimizing the checkout experience.

**Comment by AoxoA-Create** [comment]
Maybe revisit this again sometime.  A simple, small "Delete" or "Remove" text for each item wouldn't clutter things visually.  

The problem best presents itself with a large gallery of prints (maybe a wedding) where the customer has increased the qtys of multiple items.  Lets say the customer increases each item by qty 5 (copies for various family members).

If they decide to thin out the order......what a pain. To delete 20 items, the customer has to click the minus button 5 times for each of the 20 different items.  That's 100 clicks vs 20 if you have a way to delete single items.

Besides, most people are familiar with Apple, Amazon or Walmart checkout.  People are accustom to being able to delete line items with one click.  It is a normal and expected feature for checkouts.  The user experience is diminished without it.

If Apple can make it look none obtrusive, so can GPP:

![screen shot 2016-05-08 at 10 42 01 am](https://cloud.githubusercontent.com/assets/18253020/15098767/687e39e2-150a-11e6-8c1d-f9691baba4f0.png)

**Comment by thadallender** [comment]
That's all true. We'll discuss again this week. Thanks for the feedback!
