### ISSUE TITLE
Only show "Save to Lightbox" if Lightbox page is enabled

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#762]
Don't show "Save to Lightbox" when the Lightbox Page is set to none.

Screen shot of Sell Media General Settings Lightbox Page set to None:

![screen shot 2016-05-07 at 10 08 14 am](https://cloud.githubusercontent.com/assets/18253020/15092866/fe11b580-143b-11e6-90f0-811d7fedc7e1.png)

Screen shot showing where users can "save to lightbox" even though the Lightbox Page is not enabled:

![screen shot 2016-05-07 at 10 07 39 am](https://cloud.githubusercontent.com/assets/18253020/15092868/04b48f7a-143c-11e6-8359-8b407d7c7be1.png)

**Comment by thadallender** [comment]
Good suggestion. We'll implement this in the next release.
