### ISSUE TITLE
Cart Needs to Show Item Size

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#763]
I offer two print types (Photographic Prints and MetalPrints) in various size options for each item.  I use the Name feature in the Price Group to differentiate between the two. One set named "Photographic Print" and the other "MetalPrints".

In this example I added a 4x5 and an 8x10 Photographic Print to the cart.

The good things:
1.	The item Name is shown:  Hangism I
2.	The Name that I created in the Sell Media Settings (price group) is displayed: “Photographic Print” 

The problem:
1.	The size I set up in the Sell Media Settings (price group) is not being displayed.

![screen shot 2016-05-07 at 10 43 58 am](https://cloud.githubusercontent.com/assets/18253020/15093061/5cc2e400-1441-11e6-8dc9-789ad9e74a4c.png)

**Comment by AoxoA-Create** [comment]
When will you display the item size in the cart?

**Comment by thadallender** [comment]
Sizes are already in fact displayed on the Checkout page. Give it a test here:

http://demo.graphpaperpress.com/sell-media/photos/water/

Do you have the latest versions of all plugins?

**Comment by AoxoA-Create** [comment]
Interesting.  That is not working on mine.  Try it here:  https://aoxoa.co/obtain/

The size you do see is part of my Price Group Name (that was my work around).

My plugins appear to be current.

![screen shot 2016-08-08 at 11 10 41 am](https://cloud.githubusercontent.com/assets/18253020/17487122/15d9656c-5d59-11e6-91a6-53341b5c9842.png)

**Comment by AoxoA-Create** [comment]
lol, nope it is actually not working.  You demo's Price Group Names are set up as 4x6, 6x8, etc...  So it is displaying the Price Group Name.  

What i'd like is to display the size that is entered in the price group size fields.  Then I won't have to enter a size in the Price Group Name field.

**Comment by AoxoA-Create** [comment]
I am going to close this because---as determined with issue https://github.com/graphpaperpress/Sell-Media/issues/778 ---I'll add in the size to each Price Group Name (re. each price group name is required to be unique, etc...).  Therefore, the size will show up in the cart.

I assume everyone will want to do it this way. Otherwise they will run into the same issue I had.  Maybe it should be suggested in the instructions.

**Comment by thadallender** [comment]
Totally agree. We need to either clarify with better on-page instructions or change the UX to return error messages when it fails. Thanks for the feedback!

**Comment by AoxoA-Create** [comment]
FYI:  I wasn't able to use a format with quotation marks (example:  4" x 6") in the Price Group Name field.

So instead I used 4x6 inch.
