### ISSUE TITLE
Gallery displays without spaces on mobile devices

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#764]
A gallery displays without spaces between the images on mobile devices  A collection displays with spaces.  I am using the Albedo Theme.  http://aoxoa.co/

![screen shot 2016-05-09 at 9 15 12 pm](https://cloud.githubusercontent.com/assets/18253020/15134235/d284067a-162f-11e6-8bde-655b51e54e96.png)

**Comment by thadallender** [comment]
Pretty sure we resolved this in a past update. Please confirm on your website, since it can also be theme-related.
