### ISSUE TITLE
Quick View overlay not consistant

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#765]
In a gallery the quick view overlay appears on top of the thumbnail.  In a collection it displays at the bottom.

Example from gallery:
![screen shot 2016-05-09 at 9 16 02 pm](https://cloud.githubusercontent.com/assets/18253020/15134255/06833a36-1630-11e6-9721-926e22b2e772.png)

Example from collection:
![screen shot 2016-05-09 at 9 16 16 pm](https://cloud.githubusercontent.com/assets/18253020/15134257/090786cc-1630-11e6-8284-f450204e2589.png)

**Comment by thadallender** [comment]
What theme are you using? This is probably just a simple theme conflict that can fixed with a CSS float.

**Comment by thadallender** [comment]
This looks to be a conflict with our Maginifier CSS. Change:

.sell_media_image-wrap {
 float: left;
}

to

.sell_media_image-wrap {
 float: none;
}

**Comment by AoxoA-Create** [comment]
Yep.  Just placed `.sell_media_image-wrap { float: none; }` into the Custom CSS panel and problem solved.
