### ISSUE TITLE
Want Item Name (title) in Cart, etc..

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#766]
When creating single items I use the title as the items name (i.e. Panism I, Panism IV, Panism X!, etc...).  Therefore, the item name is shown on single item pages and if added to the cart.  Cool, I like that.

If images are loaded as a gallery, I loose the ability to have the items name on the single item page and in the cart.  Instead, the gallery title is used. 

Clicking to a single item from the gallery, I’d like it to display that item’s name as the title instead of the gallery’s name. 

Same goes for when I add a gallery item to the cart. In the cart, it shows the gallery title followed by a number.  I assume the number references the individual item in the gallery.  I'd like a name instead of a number or replace the gallery title/number with the individual items title (name).

**Comment by thadallender** [comment]
We're doing a major rewrite of the entire front-end UX in javascript. We'll be showing the name of the attachment in QuickView and on the Checkout page, not the gallery name.
