### ISSUE TITLE
Buggy when trying to delete payments

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#767]
### I was trying to move my test payments to trash with a bulk action

![screen shot 2016-05-09 at 9 37 27 pm](https://cloud.githubusercontent.com/assets/18253020/15134864/7b9218c4-1635-11e6-9639-ce4a773810fc.png)
### Directed to a message saying I did not have permission

![screen shot 2016-05-09 at 9 37 50 pm](https://cloud.githubusercontent.com/assets/18253020/15134861/73f06ae4-1635-11e6-8bba-8f3f91861b16.png)
### Went back to try again.  Directed to a page saying I can’t edit cause those items are in trash.

![screen shot 2016-05-09 at 9 39 41 pm](https://cloud.githubusercontent.com/assets/18253020/15134852/6c648ac6-1635-11e6-9e46-3cd60261c3a6.png)
### Went to trash and was able to delete.

![screen shot 2016-05-09 at 9 39 58 pm](https://cloud.githubusercontent.com/assets/18253020/15134847/664d2120-1635-11e6-854a-88c1df4be0c8.png)

**Comment by AoxoA-Create** [comment]
I updated to Sell Media Version Version: 2.2.1 and retested.  Not as buggy this time.

1)  moved payment item to trash (Sell Media > Payments)
2)  Browser displayed a page with the following message

![screen shot 2016-05-11 at 2 51 37 pm](https://cloud.githubusercontent.com/assets/18253020/15194455/8deba202-1788-11e6-816a-69cc09b0d9a8.png)

3) Used the browser back button to return to payments page.
4) Refreshed browser.
5) The payment item was, in fact, moved to the trash
6) went to delete permanently

![screen shot 2016-05-11 at 2 52 38 pm](https://cloud.githubusercontent.com/assets/18253020/15194512/d9dfa74e-1788-11e6-868e-54120d4897fc.png)

7)  no issues to delete.  Successful.

**Comment by rickalday** [comment]
Fixed in a360b36fbd4e6e95be6450484d0245c1cc72117c
