### ISSUE TITLE
hide a collection from being listed on archive pages

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#771]
How do I hide a collection from being listed on archive pages?

This documented advice is not working, “Click Sell Media -> Collections -> Add New and check the “Hide” option.”

I don't see a "Hide" option.

**Comment by thadallender** [comment]
We'll look into this.

**Comment by rickalday** [comment]
Collections can be password protected and thus hidden from listings and search results.

**Comment by AoxoA-Create** [comment]
Can I hide the collection from being listed on the archive pages AND have it visible in search results?

**Comment by rickalday** [comment]
Yes, a collection can be hidden but search results return only images, not collections so if an image is in a hidden collection it will still show up in search results.
