### ISSUE TITLE
Add a “Search Form” tab to the “Filters Shortcode”

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#772]
How do I add a “Search Form” tab to the “Filters Shortcode”?  So, clicking the added search form tab will display the search form in the filter drop-down.

Something like this:

![screen shot 2016-05-14 at 6 59 16 pm](https://cloud.githubusercontent.com/assets/18253020/15271325/c841db88-1a08-11e6-81c9-ca26561ef79f.png)

**Comment by thadallender** [comment]
You would need to know PHP, JavaScript, CSS, and know how to create a WordPress plugin. It's not possible currently.

**Comment by AoxoA-Create** [comment]
Can we make this a feature or enhancement request to be considered in the future?

**Comment by thadallender** [comment]
Many themes already include a search form in the header or sidebar. If you add another search form to the same page, it causes lots of issues. So unfortunately, I don't think we'll be adding this to the shortcode.

**Comment by AoxoA-Create** [comment]
I am not talking about that type of search form.  I am talking about the one used to display a search form exclusively for searching items for sale within Sell Media: [sell_media_searchform].

You already have this in production.  And, so far, it does not cause any issues.  Just would like it WITH IN the filter shortcode. Do you understand what I am asking?
