### ISSUE TITLE
Keyword Imports on Galleries

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#776]
Keywords are not being imported when you upload multiple images (containing keywords) to create a gallery in Sell Media.

Steps To Reproduce:

1. Add keywords to images in Photoshop.
2. Upload multiple images to Sell Media, creating a gallery.
3. Save the post.

Result:

No keywords are assigned to the gallery post and searching for that keyword doesn't return any results showing any of the attachments uploaded to the post. Also, the keyword taxonomy page in WordPress shows the "count" column of 0 for these missing keywords. Viewing one of these keyword terms on the front end results in "Nothing Found".

Expected Result:

Keywords that appear in ALL uploaded images should be extracted and applied to the post_id. All keywords on uploaded images should only be applied to that specific attachment_id.

**Comment by KellyRich** [comment]
I am having the same issue. has it been resolved?

**Comment by maharzan** [comment]
This is still not working with the changes on search. There are keywords in the gallery post but searching the keywords returns 0 results. The keywords aren't imported to attachments as well. The SM filter shows all the keywords from the gallery posts as well but majority of those keywords when clicked returns nothing found error. If how the gallery works is how it should it, then we should hide the keywords from the filter. Or else, we need to fix how the gallery keywords should work.

![test](https://cloud.githubusercontent.com/assets/883993/19675313/52973164-9aad-11e6-91a0-2e056c72d815.png)

**Comment by thadallender** [comment]
Version 2.6.7 will fix this.
