### ISSUE TITLE
Thanks shortcode - setcookie causing headers already sent warning 

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#777]
setcookie function in the sell_media_thanks page shortcode is causing a warning. This is because shortcodes don't sent headers at all, so the cookie isn't updated.

We should move this function into the IPN callback from PayPal and out of the thanks shortcode. 

Warning Message:

headers already sent by (output started at /var/www/testing.graphpaperpress.com/htdocs/wp-includes/class.wp-styles.php:127) in /var/www/testing.graphpaperpress.com/htdocs/wp-content/plugins/sell-media/inc/shortcodes.php on line 54

**Comment by codearryaas** [comment]
setcookie function has been removed from the thank you page shortcode. 
cookie is already cleared from sell_media_clear_cart_after_payment function in helper.php
