### ISSUE TITLE
Download / Import Sell Media Settings

### ISSUE THREAD

**Issue by AoxoA-Create** [graphpaperpress/Sell-Media#779]
Recently I had to deactivate plugins as part of a trouble shooting procedure.  I loose too many settings in Sell Media when deactivated and then reactivated.  

One of my plugins (WP Rocket) has a "Download" button (settings Exporter) and an "Upload" settings importer button.  

**Screen shot:**
________________________________

![screen shot 2016-09-01 at 8 41 40 am](https://cloud.githubusercontent.com/assets/18253020/18169573/57633e70-7020-11e6-9d3b-beb22e99d5d8.png)
__________________________________

Other plugins simply keep my settings upon reactivation.  I assume settings would be lost if I deleted the plugins----but not when deactivating.

Can you make Sell Media user friendly in this manner?

**Comment by thadallender** [comment]
We're removing the function that removes plugin settings on plugin deactivation. So this won't be needed in the future.

**Comment by AoxoA-Create** [comment]
It did save some settings but not all of them.  When I reactivated it I lost some settings:

**- Setting > General:** Lost all my setting for the page drop-downs (checkout page, Thanks Page, etc…). I used my own custom page names but Sell media create its own defaults and used those.
**- Settings > License:** Lost my email and License Key

As far as I can tell the other setting are the same.
