### ISSUE TITLE
Search Pagination Issue

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#780]
Pagination on Search isn't working correctly. For example, search for "earth" on the Sell Media demo site:

https://demo.graphpaperpress.com/sell-media/search/

Then click Page 2. The url becomes:

https://demo.graphpaperpress.com/sell-media/search/?paged=2&keyword=earth&collection

This leads to a "Page Not Found." Looks like search is querying the first parameter "paged=2"

**Comment by KellyRich** [comment]
Rick helped me fix this he said to do the following to fix it: 
 make sure your search page is not titled "Search".  Change the page title and the URL to anything else but "search".

**Comment by rickalday** [comment]
Fixed in latest version.
