### ISSUE TITLE
When viewing an image in a collection the arrow keys to go back and forward are not loading images from the same collection.

### ISSUE THREAD

**Issue by KellyRich** [graphpaperpress/Sell-Media#782]
1. Click on Collection, (I chose Sleeping Pets to best illustrate the issue. 
   ![image](https://cloud.githubusercontent.com/assets/22874503/19421103/ca09ad14-93c6-11e6-8f19-3c4d0adf234e.png)
2. Choose an image from the list of thumbnails: I chose valentine sleeping lab 4th image on top row. note it has a valentine sleeping image on left, and a white kitten on blue on right. I have cclicked on this iamge to go to large view.
   ![image](https://cloud.githubusercontent.com/assets/22874503/19421122/48acc4da-93c7-11e6-86f9-7d56caae3426.png)
3. Look below large view lab sleeping and you will notice you have two arrows that give you the option to go back or forward to see more images in the collection. However it does not show more images from the sleeping pets collection, it goes back and forward to images that are in the Media (that are not sleeping pets.)
   ![image](https://cloud.githubusercontent.com/assets/22874503/19421139/ae7035f4-93c7-11e6-9642-1e11e652affc.png)
4. When you click the left arrow to see an image that (I was assuming) was from the same sleeping pets collection, you get an easter lab. It appears it is loading images from the order they were uploaded, not from the collection.
   ![image](https://cloud.githubusercontent.com/assets/22874503/19421167/5f611144-93c8-11e6-95d9-fc8e9bb1d24b.png)

**Comment by codearryaas** [comment]
While going to detail page of an image, next and previous image depends upon the order of post from backend not from collection. After going to detail page it breaks connection with collection page.
