### ISSUE TITLE
Collection filter paging ends in blank list

### ISSUE THREAD

**Issue by maharzan** [graphpaperpress/Sell-Media#783]
There is a paging but clicking next on the collection list leads to blank tab as the screenshot.

I have 16 total collections with 4 collections with 0 posts. So, its showing 12 collections but the paging might be taking the total number into consideration, thus the next page.

![test](https://cloud.githubusercontent.com/assets/883993/19675360/a10ccbc4-9aad-11e6-9bc5-f8fc1399f968.png)

**Comment by thadallender** [comment]
Fixed in Sell Media 2.2.7 or higher.
