### ISSUE TITLE
Remove Keywords from SM item

### ISSUE THREAD

**Issue by maharzan** [graphpaperpress/Sell-Media#784]
To remove the confusion over where keywords should reside, we will have to remove the Keywords section in the SM CPT.

![test](https://cloud.githubusercontent.com/assets/883993/19678573/0a9f8bfc-9abe-11e6-8c41-1b50ea97a02e.png)

**Comment by thadallender** [comment]
Yep, that's the plan.

**Comment by thadallender** [comment]
Fixed in Sell Media 2.2.7 or higher.
