### ISSUE TITLE
Keywords not being imported

### ISSUE THREAD

**Issue by maharzan** [graphpaperpress/Sell-Media#785]
I added keywords to a photo and uploaded it to sell media but that image doesn't have keywords in the Media page.

As you can see the keywords are there in the image properties on the left but after uploading and saving to sell media item and looking to Media page, I don't see the keywords there.

Please check on your end and verify.

![screen shot 2016-10-25 at 2 33 24 pm](https://cloud.githubusercontent.com/assets/883993/19679051/043bb13a-9ac0-11e6-956f-a4dc1ff6426b.png)

**Comment by maharzan** [comment]
I added the keywords from Lightroom, if that matters.

**Comment by maharzan** [comment]
tried with photoshop as well, description is importing but keywords are empty.

**Comment by maharzan** [comment]
When I deactivate and activate SM, the keywords are imported to the image attachment and the post. interesting. I am not sure how this is working. I think we need to do keywords import when they save the post as well, not just on import.

**Comment by thadallender** [comment]
Keywords are imported to attachments three ways in 2.6.7 or higher:

1. **Legacy Keyword Migration** - When users update from 2.6.6 or earlier, keywords from sell_media_item entries with only one attachment are copied to the respective attachment post type.
2. **File Upload** - Once you have 2.6.7 installed, keyword are imported from the file's metadata during file upload into Sell Media.
3. **Manually Added** - Once you have 2.6.7 installed, users can manually add keywords in the Media Library.
