### ISSUE TITLE
The no results text should be bigger or highlighted

### ISSUE THREAD

**Issue by maharzan** [graphpaperpress/Sell-Media#786]
Somehow this text seems invisible with the filter showing at the bottom. I was wondering why the search wasn't working at first. So the "Sorry, no results. Explore related products below." should be bigger in size or highlighted, like a reddish background color.

![test](https://cloud.githubusercontent.com/assets/883993/19684548/84803ce6-9ad7-11e6-8fab-54581ba2fff2.png)

**Comment by thadallender** [comment]
e1be751367ea322e4bca51d780c19654ca7520da fixes
