### ISSUE TITLE
Manual Payments

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#790]
Sellers need a way to record manual payments in Sell Media.

1. Add an "Add Payment" button on the Payments page, just like Posts and Pages.
![screen shot 2016-11-04 at 10 08 06 am](https://cloud.githubusercontent.com/assets/302884/20009624/94d5df3c-a27b-11e6-8ea6-f68145a62928.png)
2. The "Add Payment" page should NOT show up in the WP/Sell Media menu.
3. Add these fields:

- Product Name & ID (Select field, use data-types on options to help change fields below)
- Media File Name & ID (Select field, use ajax to get _sell_media_attachment_id of the post after Product Name & ID is selected)
- Price/Size (Select field, use ajax to get available sizes in the Product's assigned price group)
- License (Select field, use ajax to show a list of licenses assigned to the Product)
- Type (Select field, download or shipped product)
- Buyer (Text field, Buyer ID or Email. This will be used to show downloads to the user on customer Dashboard. Provide a link to Add User page in description).

**Comment by codearryaas** [comment]
This feature has been added in an addon.
