### ISSUE TITLE
Check UTF character encoding from PayPal IPN

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#791]
If users have their PayPal account IPN Character formatting set to anything other than UTF-8, no transactional data is saved with the IPN in Sell Media. Transactions will be recorded without any data and a price of $0 and empty emails are sent to buyers.

We should add a check/action in the PayPal IPN class that sends the site admin an email IF character encoding is anything other than UTF-8 in the IPN response from PayPal. We could use this function convert IPN messages to UTF-8:

http://php.net/manual/en/function.mb-convert-encoding.php

The email sent to admins should tell them to change character encoding to UTF-8:

> You have an invalid PayPal setting that is preventing payments from being recorded in Sell Media. You need to set the IPN message format to “UTF-8” from your PayPal profile by doing the following:
> 
> 1. Log into your PayPal account
> 2. Go to your profile
> 3. Look for the “PayPal button language encoding” section under the My selling tools
> 4. Make sure your website language is set to the correct language
> 5. Click the more options button
> 6. Make sure encoding is set to UTF-8
> 7. Then save settings
> 8. Confirm it's working by trying another purchase
> 

Related ticket:

https://app.intercom.io/a/apps/kylisdd0/inbox/conversation/6525776009?nsrc=slack

**Comment by codearryaas** [comment]
I think this issue has been solved.
