### ISSUE TITLE
Dialog box height 

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#797]
The [sell-media-dialog-box](https://github.com/graphpaperpress/Sell-Media/blob/f5c2482da4bfacb5e8e433377fae5c28aeab6840/sass/sell_media.scss#L840) container should have a max-height and max-width limit using viewport units (vh).  Some themes calculate a very large DOM size that can lead to a funky display for elements that use 100% width or height.

**Comment by codearryaas** [comment]
I think this issue is solved.
