### ISSUE TITLE
Fresh Install, No Keywords

### ISSUE THREAD

**Issue by dvrcthewrld** [graphpaperpress/Sell-Media#799]
I've tested this on two different servers, with both PHP 5.6 and 7.  A fresh install of WP 4.7.2 and Sell Media 2.3.1 (and some earlier versions) results in an install where Keywords don't show up in the product edit section.  And the option to have a Keywords column in the admin area is also missing.

**Comment by thadallender** [comment]
Keywords are attached to Media, and not Sell Media Items. Please check your Media and confirm you see them.
