### ISSUE TITLE
Filename shown to buyer with S3 enabled

### ISSUE THREAD

**Issue by dvrcthewrld** [graphpaperpress/Sell-Media#800]
With the S3 extension enabled, the filename shown to buyers on the Thank You and Dashboard pages includes S3 key info.  It looks awful.  To fix it…

In inc/class-payments.php, around line 450, change from-to
`$filename = basename( $filename[0] );`
`$filename = array_shift(explode('?', basename($filename[0])));`

**Comment by tmvc** [comment]
Guys, this issue is still persistent. Please fix it with the next release as it's an effort of less than a minute and annoying for the users...

**Comment by rickalday** [comment]
@tmvc this and other updates have been committed in the dev branch.  Feel free to download a copy of the [class-payments.php](https://github.com/graphpaperpress/Sell-Media/blob/dev/inc/class-payments.php) file.
