### ISSUE TITLE
Non-purchased downloads not protected?

### ISSUE THREAD

**Issue by MYSTERYouse** [graphpaperpress/Sell-Media#807]
Let's say user makes a purchase and receives the download link in a following form

http://testweb.com?download=1R152066MH932345F&payment_id=60&product_id=15&attachment_id=18&size_id=4

Once you click the link, you can download the given file in a given resolution of your respective product.

When a smart-ass user starts to play with the data, he might discover that by playing with the ids, he is actually able to download any file in any resolution. It seems only a valid payment_id is required for any download. It's easy to get the needed ID of the picture just by looking up the CSS class on any page where the picture is displayed.

Is there a way how to fix this by always requiring the combination of valid paymentID/productID for example?

**Comment by codearryaas** [comment]
This issue has been fixed. I'll be released in next version.
