### ISSUE TITLE
More options on cart page

### ISSUE THREAD

**Issue by kevinspectrum** [graphpaperpress/Sell-Media#809]
Would be nice to be able to add more custom options on the cart page.
 ei: Model / Property  release (y) (n)
Editorial use only disclaimer
Usage / Location / Fee calculator
I agree to terms and conditions check box

**Comment by thadallender** [comment]
We're doing a major rewrite of the entire front-end UX, which includes the Checkout page. New features will include:

1. Usage fee calculator on Checkout page
2. Agree to terms and conditions on Checkout page.

The model/property release details can be added in the content area of the entry itself. The editorial use disclaimer can be added in the description field of the License.
