### ISSUE TITLE
no keywords  

### ISSUE THREAD

**Issue by erikksson** [graphpaperpress/Sell-Media#813]
I made a fresh local install with wordpress 4.75. Somehow the keywords part is broken. keywords are neither shown on a products detail page, nor in the sell-media keyword-widget.
(yes I have checked, within the media the keywords are applied correctly.)

already in my 4.74 install, there is some problem when displaying a single product. I did some debugging on the taxonomy-information and it seems, depending on what you do before, In most cases there are not all three datas available ( creator, collection, keywords) ... at least one seams to be missing somehow (didnt fined a regularity yet)

**Comment by thadallender** [comment]
We have tested products with both a single image and products containing a gallery of images and in both cases, Keywords are both imported and displayed correctly on the website. The only way that Keywords would not show up on the single product page is if:

1. You don't have the Sell Media Keywords widget active in a specific widget location.
2. Your theme doesn't have the widget location coded into the product template file.
3. You have a plugin conflict that is confusing the WP query.

You can rule out theme conflicts by switching to one of the Default WP themes and checking the single product page.

You can rule out plugin conflicts by deactivating all plugins that might be in conflict and checking the single product page.

Let me know what you find.
