### ISSUE TITLE
Derive original source file dimensions from protected file

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#814]
A user reported this in our support forum:

"I am uploading a jpeg whose dimensions are 6000x4000, but when I go to select a size to download from my page, the largest size available is medium and shows that the original file size, also available for download, is only 2048x1365."

We should be deriving the file size of the original source file from the protected directory, not the public directory.

**Comment by rickalday** [comment]
Fixed in dev branch.
