### ISSUE TITLE
Expose the upload meta field to rest API

### ISSUE THREAD

**Issue by Archie22is** [graphpaperpress/Sell-Media#816]
Hey guys, 

This is not really an issue. I want to post to Sell Media from a third party tool. So far I was able to get the post title, author, id, description and the categories to appear on the WP-JSON URL. I am however struggling to expose the Multiple images field (sell_media_files_meta_box). 

It what I am hoping to do attainable? This is what I want to post to from a remote application: 
Screenshot
http://prntscr.com/fj9ejb / [http://prntscr.com/fj9ejb](http://prntscr.com/fj9ejb)

**Comment by thadallender** [comment]
That might be tricky. Here's why: Files that are uploaded into Sell Media
use core WP functions. The files (saved as "attachment" post types in WP)
each get their own ID. Those attachment ids are all saved to the
_sell_media_attachment_id post meta field. So, in order for your
application to upload images, you'll have do the following things:

1. Upload each attachment into WP from your application.
2. Put those attachment ids into an array.
3. Create your Sell Media entry.
4. Pass those attachment ids along as post meta (_sell_media_attachment_id).

That's how it would need to work conceptually.

**Comment by Archie22is** [comment]
Thank you @thadallender !
