### ISSUE TITLE
Thumbnails for non-image products.

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#817]
Still getting missing thumbnails for certain file types such as PDF and zip.
- Missing thumbs Checkout and Lightbox pages - Check the last two commits on my fork: https://github.com/rickalday/Sell-Media
- Missing thumbs in all widgets
- Missing thumbs in search results links (Do a search for a PDF or zip product, the results page will show a thumbnail but if you click one of the thumbnails to view the end product the image will be missing)

**Comment by codearryaas** [comment]
Fixed thumb issue on checkout, lightbox pages, all widgets & in the search.
Please check in Dev branch.
