### ISSUE TITLE
Mailchimp Plug-in

### ISSUE THREAD

**Issue by colourbalanceim** [graphpaperpress/Sell-Media#819]
I entered the Mailchimp API into my settings and received an error 500 after trying to save the update. I first reached out to WordPress to discuss the issue. They eventually recognized the issue originated from the sell-media-mailchimp plug-in and deactivated it in my account, so that I could regain access to the wp-admin site.

**Comment by thadallender** [comment]
This was resolved last month. We updated the MailChimp API with a new version.
