### ISSUE TITLE
PriceTables / feature request

### ISSUE THREAD

**Issue by erikksson** [graphpaperpress/Sell-Media#820]
offering a good overview about prices for images is important. Pricetables are necessary and common for that these days - not having such is quite a market-disadvantage.
Please add an easy possibility  to implement them.

![pricetables](https://user-images.githubusercontent.com/28840900/28537536-8935aa5a-70ab-11e7-8c61-c266e2406ad2.png)

**Comment by thadallender** [comment]
There are many existing ways to add pricing tables to WordPress:

https://wordpress.org/plugins/search/pricing+table/

**Comment by philllie** [comment]
that is interesting.
i would also like to have such pricetables with sell-media. But as a user (not a developper) I haven't got a clue, how to connect data from sell-media into those plugins.
As most users might be in the same situation i assume there is a tutorial how to do so? or can you explain it to us? (my theme uses the visualbakery plug-in)

thank you
