### ISSUE TITLE
Big uploads cause gallery to become uneditable

### ISSUE THREAD

**Issue by thadallender** [graphpaperpress/Sell-Media#835]
When users upload lots of photos at once, and the upload process hangs for whatever reason, adding/editing gallery items becomes impossible. Possibly related to server timeout and incomplete metadata.

**Comment by thadallender** [comment]
Likely related: #823

**Comment by rickalday** [comment]
Fixed in 621057b7e171128dd6ba165c270ce8a8ed8266b5
