### ISSUE TITLE
So horrible! Could the original file name and directory be protected from hacker's guessing?

### ISSUE THREAD

**Issue by pendave** [graphpaperpress/Sell-Media#841]
Here're screenshots when I use Chrome browser or Firefox.

![buz go_k6id7 m bk4](https://user-images.githubusercontent.com/1331881/36550460-5037ff0a-1830-11e8-89f6-8fb562c9e706.png)
![s93r_ac6 gs 9izwfg62vn](https://user-images.githubusercontent.com/1331881/36550471-5558c74e-1830-11e8-8e17-de44e706ecd4.png)

Same thing happens if you press F12 on the browser to check the info added to the `<img` tag's attributes.
![rqff hbouay5xr9q lwr8](https://user-images.githubusercontent.com/1331881/36550734-f4472bb6-1830-11e8-8173-3fc9ca52d7c5.png)

The hacker could get some nice images in good quality without watermark!

https://demo.graphpaperpress.com/sell-media/files/2016/03/image-76203416-620x349.jpg

https://demo.graphpaperpress.com/sell-media/files/2016/03/image-76203416.jpg

Just remove `-620x349` to get a better one.

So horrible!
Good quality images without watermarks are leaking out.........

Another bug is the `<img` tag's attribute 

> alt

 is always null... 

================
BTW, I can't find this setting according to your **sell-media/readme.txt**

> = How do I password protect an item? =
> 
> The Password Protection option is located in the Publish box when editing a Sell Media item. Click the Visibility - Public - Edit link, select Password Protected, type in a password and click Save.

Do you provide any screenshots for doing that?

**Comment by rickalday** [comment]
Sell Media moves the original, high-resolution image to a protected directory on your server. Sell Media then makes lower-resolution copies of the original image and places them the web-accessible uploads directory. The sizes of the lower-resolution images are controlled by your Settings -> Media sizes. Thieves can only steal lower-resolution copies of the image. The original file is always protected.

The image links you referenced are for the web-accessible low-res copies on our demo.
