### ISSUE TITLE
Scary issue! Huaban extension for Chrome browser could leak out the original image.

### ISSUE THREAD

**Issue by pendave** [graphpaperpress/Sell-Media#842]
If you install this extension **Huaban** on Chrome

https://chrome.google.com/webstore/detail/%E8%8A%B1%E7%93%A3%E7%BD%91%E9%A1%B5%E6%94%B6%E8%97%8F%E5%B7%A5%E5%85%B7/imamemhokkdleoelohnmkimbmpfglcil

When **Sell Media Magnifier** is active, there're trouble.

![kiin 1 3ali rw zs x67y1](https://user-images.githubusercontent.com/1331881/36574443-d3d938ce-1880-11e8-9109-b9f2dd7a23f4.png)
![6yj1lie ge1y gwh 3wo041](https://user-images.githubusercontent.com/1331881/36574448-d790ef02-1880-11e8-988c-5f24f380321b.png)

The image on the far right sniffered out by **Huaban extension** is the large original image without watermark.

**Comment by rickalday** [comment]
Same as https://github.com/graphpaperpress/Sell-Media/issues/841
The Magnifier uses the web-assecible "Large" version of the image.  "Large" as defined in Settings -> Media.
