### ISSUE TITLE
Script Blocker extension for Chrome is a killer to the original large image

### ISSUE THREAD

**Issue by pendave** [graphpaperpress/Sell-Media#843]
There're many javascript block extension for Chrome browser such as:
https://chrome.google.com/webstore/detail/script-blocker-for-chrome/aakchmnmjneadkakfihibdbepehaflop

Test on page
https://demo.graphpaperpress.com/sell-media/photos/dog/
![rted 30yxvf __0](https://user-images.githubusercontent.com/1331881/36599850-a29c8a34-18eb-11e8-8599-00155ba032a5.png)

It will remove the watermark and Ctrl+U to check the source and search for <img you can see the unmasked image.
![ct8 e 8 8o1k f rs i 2](https://user-images.githubusercontent.com/1331881/36599916-cee3b0b8-18eb-11e8-85b9-d5c2cd9e259c.png)

It's easy to get the original image
https://demo.graphpaperpress.com/sell-media/files/2016/03/image-76203416-940x529.jpg

Also "`Block scripts in browser`" works:
![a 8_gp svfp5_ n e9 5z2](https://user-images.githubusercontent.com/1331881/36600614-bb3414ca-18ed-11e8-9afd-006bcef8eb1d.png)

![5 gzuu_kudabo7g7 4 r](https://user-images.githubusercontent.com/1331881/36600837-5adf1be6-18ee-11e8-8c17-75fe0400c14a.png)

So it's not safe at all, what can replace the watermark plugin for sell media???

**Comment by thadallender** [comment]
There is an option in the watermark extension to use a PHP watermark. This embeds the watermark in the image. You cannot undo this watermark. The option you are referring to is the JavaScript option. This is a client side watermark and not a fully protected watermark, but it is reversible.

Also, the original image size is always protected. The source file you are referencing is not the actual full size protected image. You are referencing the large public web accessible image file.

**Comment by pendave** [comment]
The PHP watermark option could not handle with .png (transparent background)?

Here's effect I got when I upload .png format:
![_ shfz1t70cn40j2_gom](https://user-images.githubusercontent.com/1331881/36627249-eb7eb51c-197a-11e8-9ba5-c927acd52a4d.png)

No thumbnail image displayed below the Filter Tabs.

So what formats are supported?

**Comment by rickalday** [comment]
Use a transparent 24-bit PNG image.
