### ISSUE TITLE
Warnings and blank page when creating or updating products

### ISSUE THREAD

**Issue by rickalday** [graphpaperpress/Sell-Media#852]
In the latest version, whenever I create or update a product I get these warnings:
Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/gpp/wp-content/plugins/sell-media/inc/admin-items.php on line 537

Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/gpp/wp-content/plugins/sell-media/inc/admin-items.php on line 538

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/gpp/wp-content/plugins/sell-media/inc/admin-items.php:537) in /Applications/MAMP/htdocs/gpp/wp-includes/pluggable.php on line 1216

The product is created or updated despite the warnings.
Using latest version of WP and Sell Media
PHP 7.1.12
MySQL 5.6.38

**Comment by thadallender** [comment]
If you disable WP_DEBUG, this shouldn't happen. Regardless, looks like we need to add a check in admin-items.php for marketplace settings.

**Comment by rickalday** [comment]
Without WP_DEBUG I just get a blank page.

**Comment by rickalday** [comment]
Fixed in dev branch 20321289f4991770c313e4f737d4c6f78ef2c7d4
