### ISSUE TITLE
helper.php not PHP 7.2 compatible

### ISSUE THREAD

**Issue by HaraldWalker** [graphpaperpress/Sell-Media#855]
When using PHP 7.2.7, the helper.php script throws following error on an item page:
`Warning: count(): Parameter must be an array or an object that implements Countable in /[...]/wp-content/plugins/sell-media/inc/helpers.php on line 362`

Downgrading to 7.0 solves the problem.

**Comment by rickalday** [comment]
Fixed in dev branch: 591e0f168a5d4ea6d0393a0d0ea771926ccb7b9f
