### ISSUE TITLE
Add widget to show keywords of an image 

### ISSUE THREAD

**Issue by HaraldWalker** [graphpaperpress/Sell-Media#857]
Feature request:

Current keywords widget shows all known keywords. Instead I want to show only the keywords of the current product/image on the detail page so that a visitor from there can find matching similar products/images.

I've already created this and if it seems like a useful widget to have I'd be happy to provide it or otherwise release it myself as a WP plugin.

**Comment by rickalday** [comment]
This is already included in the plugin.  Go to Sell Media -> Settings -> File Info -> Yes.
This will show the current image EXIF data, including keywords.
