### ISSUE TITLE
IPTC creator not being read

### ISSUE THREAD

**Issue by treysea** [graphpaperpress/Sell-Media#859]
I can see that the creator is supposed to be assigned to the image in this function: parse_iptc_info()

However our creator is not being set during upload. The metadata exists in the correct field.

Keywords are assigned as expected.

![screenshot_2019-0618_4539](https://user-images.githubusercontent.com/2193578/59732877-cf794f80-9200-11e9-87ec-d3165c292ee4.png)

**Comment by thadallender** [comment]
This has been fixed on "master" branch. Deploying to WP.org soon.
