### ISSUE TITLE
Fatal error on edit page with checkout shortcode

### ISSUE THREAD

**Issue by to-sky** [graphpaperpress/Sell-Media#861]
Hi, I found a bug.
When I add the shortcode [sell_media_checkout]. This page is available to checkout actions but if I want to edit page I get the error.

Fatal error: Uncaught Error: Call to a member function getItems() on null in /.../wp-content/plugins/sell-media/inc/shortcodes.php on line 185

**Comment by maharzan** [comment]
This should ow be fixed with 2.4.3
