### ISSUE TITLE
Critical Error - must be compatible with ArrayAccess::offsetExists($offset)

### ISSUE THREAD

**Issue by djalondon** [graphpaperpress/Sell-Media#945]
Update today has caused the following error which has set the website to show a Critical Error message.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.3.1
Active theme: Qua (version 1.0.0)
Current plugin: Sell Media (version 2.5.8)
PHP version 7.4.33

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 89 of the file http://{ domain } /public_html/wp-content/plugins/sell-media/inc/libraries/wp-session/class-recursive-arrayaccess.php. Error message: Declaration of Recursive_ArrayAccess::offsetExists(mixed $offset): bool must be compatible with ArrayAccess::offsetExists($offset)

**Comment by maharzan** [comment]
please update your pho version to 8.0

**Comment by maharzan** [comment]
or for the time being : update inc/libraries/wp-session/class-recursive-arrayaccess.php with this file 
https://raw.githubusercontent.com/graphpaperpress/Sell-Media/8108e5f336b5ac159683af73655e9e4ca4db348c/inc/libraries/wp-session/class-recursive-arrayaccess.php

**Comment by djalondon** [comment]
OK, thanks for the quick response. Seems there is another plugin that doesn't work on PHP 8.0 so I updated the php file you provided and that worked, thank you
